// Projects Portfolio Dataset for Walton Consultants & Contracting
import {
  Building2,
  MapPin,
  Calendar,
  Layers,
  Award,
  ShieldCheck,
  Truck,
  Compass,
} from "lucide-react";

export const WALTON_PROJECTS = [
  {
    id: "punjab-arterial-interchange",
    slug: "punjab-arterial-interchange",
    title: "National Arterial Highway Interchange & River Viaduct",
    name: "National Arterial Highway Interchange & River Viaduct",
    category: "Highways & Bridges",
    tag: "Highways & Bridges",
    eyebrow: "Federal Highway Infrastructure",
    location: "Lahore – Sheikhupura Corridor, Pakistan",
    client: "National Highway Authority / C&W Department",
    value: "PKR 14.8 Billion",
    completionYear: "2025",
    image: "/images/walton/project_01_interchange.jpg",
    heroImage: "/images/walton/project_01_interchange.jpg",
    images: [
      "/images/walton/project_01_interchange.jpg",
      "/images/walton/hero_infrastructure.jpg",
      "/images/walton/hero_transportation.jpg",
    ],
    summary:
      "A landmark multi-level cloverleaf highway interchange and 1.8km prestressed concrete river bridge. Engineered with post-tensioned segmental box girders and polymer-modified asphalt to support heavy commercial transit of over 120,000 vehicles daily.",
    overview:
      "A landmark multi-level cloverleaf highway interchange and 1.8km prestressed concrete river bridge. Engineered with post-tensioned segmental box girders and polymer-modified asphalt to support heavy commercial transit of over 120,000 vehicles daily.",
    scope: [
      "12-lane grade-separated central interchange with 4 elevated directional flyover ramps",
      "1,800-meter prestressed segmental concrete bridge over river with bored pile foundations to 42m depth",
      "Over 45,000 metric tons of ASTM Grade-60 high-tensile steel rebar placed",
      "High-speed intelligent traffic monitoring systems, LED illumination gantries, and flood drainage culverts",
    ],
    deliverables: [
      "12-lane grade-separated central interchange with 4 elevated directional flyover ramps",
      "1,800-meter prestressed segmental concrete bridge over river with bored pile foundations to 42m depth",
      "Over 45,000 metric tons of ASTM Grade-60 high-tensile steel rebar placed",
      "High-speed intelligent traffic monitoring systems, LED illumination gantries, and flood drainage culverts",
    ],
    technicalSpecs: [
      { key: "Governing Specification", value: "AASHTO LRFD Bridge Design & NHA Pakistan Standards" },
      { key: "Concrete Volume", value: "285,000 cubic meters placed with temperature control" },
      { key: "Steel Rebar", value: "45,000 metric tons ASTM A615 Grade-60 high-yield steel" },
      { key: "Piling Depth", value: "42-meter rotary bored cast-in-place concrete piles" },
    ],
    metrics: [
      { label: "Corridor Length", value: "24.5 km" },
      { label: "Bridge Span", value: "1,800 m" },
      { label: "Concrete Poured", value: "285,000 m³" },
      { label: "Safety Rating", value: "Zero LTI" },
    ],
    pillars: [
      { title: "Prestressed Box Girders", desc: "Long-span precast segmental concrete girders minimizing river piers.", icon: Layers },
      { title: "Deep Bored Piling", desc: "Foundations drilled 42m into load-bearing dense strata with polymer slurries.", icon: Compass },
      { title: "High-Volume Asphalt Paving", desc: "Polymer-modified asphalt wearing course enduring heavy freight axle loads.", icon: Truck },
      { title: "Intelligent Traffic Gantries", desc: "Automated traffic monitoring, fiber-optic telemetry, and LED illumination.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Survey & Geotechnical Drilling", desc: "Sub-surface investigation identifying bedrock depth across riverbed." },
      { step: "02", title: "Piling & Pier Cap Casting", desc: "Rotary bored piling and casting hydrodynamic bridge piers." },
      { step: "03", title: "Segmental Girder Erection", desc: "Precast girder fabrication in dedicated yard and launcher erection." },
      { step: "04", title: "Asphalt Paving & Handover", desc: "High-speed laser paving, crash barriers, and formal commissioning." },
    ],
    faqs: [
      { q: "What flood protection was engineered for this bridge?", a: "Piers were modeled for 100-year peak flood discharge with rip-rap rock scour protection around foundation piles." },
      { q: "How was freight traffic diverted during interchange construction?", a: "A multi-phase traffic management plan kept 6 lanes open at all times throughout execution." },
    ],
  },
  {
    id: "walton-twin-towers-commercial",
    slug: "walton-twin-towers-commercial",
    title: "Apex Corporate Financial Towers & Mixed-Use Complex",
    name: "Apex Corporate Financial Towers & Mixed-Use Complex",
    category: "Commercial & Urban",
    tag: "Commercial & Urban",
    eyebrow: "Commercial High-Rise Superstructure",
    location: "DHA Phase 5 Commercial District, Lahore",
    client: "Apex Holdings & Institutional Real Estate Consortium",
    value: "PKR 18.5 Billion",
    completionYear: "2024",
    image: "/images/walton/project_02_commercial.jpg",
    heroImage: "/images/walton/project_02_commercial.jpg",
    images: [
      "/images/walton/project_02_commercial.jpg",
      "/images/walton/hero_modern_architecture.jpg",
      "/images/walton/service_05_architecture.jpg",
    ],
    summary:
      "A dual 38-storey corporate financial tower complex featuring 4-level deep subterranean basements, beam-less post-tensioned floor slabs, high-performance unitized double-glazed curtain wall facades, and LEED Gold energy-efficient mechanical systems.",
    overview:
      "A dual 38-storey corporate financial tower complex featuring 4-level deep subterranean basements, beam-less post-tensioned floor slabs, high-performance unitized double-glazed curtain wall facades, and LEED Gold energy-efficient mechanical systems.",
    scope: [
      "Dual 38-storey commercial superstructures rising 145 meters above ground level",
      "4-level underground basements retained by contiguous secant pile walls and ground anchor tiebacks",
      "Post-tensioned unbonded tendon slabs providing 12.5-meter column-free panoramic floor plates",
      "State-of-the-art seismic shear wall core with hydraulic self-climbing formwork execution",
    ],
    deliverables: [
      "Dual 38-storey commercial superstructures rising 145 meters above ground level",
      "4-level underground basements retained by contiguous secant pile walls and ground anchor tiebacks",
      "Post-tensioned unbonded tendon slabs providing 12.5-meter column-free panoramic floor plates",
      "State-of-the-art seismic shear wall core with hydraulic self-climbing formwork execution",
    ],
    technicalSpecs: [
      { key: "Height & Storeys", value: "145 meters, 38 storeys above ground + 4 basement levels" },
      { key: "Structural System", value: "Central concrete shear core + ductile moment resisting frame (ACI 318)" },
      { key: "Concrete Strength", value: "C60 high-strength concrete for columns and core walls" },
      { key: "Green Rating", value: "LEED Gold Certified by USGBC" },
    ],
    metrics: [
      { label: "Built-up Area", value: "1.65M sq ft" },
      { label: "Storeys", value: "38 Floors" },
      { label: "Basement Levels", value: "4 Levels" },
      { label: "Green Cert", value: "LEED Gold" },
    ],
    pillars: [
      { title: "Post-Tensioned Slabs", desc: "Large 12.5m column-free office floor plates maximizing net leasable area.", icon: Layers },
      { title: "Ductile Shear Wall Core", desc: "Hydraulic self-climbing core forms achieving 4-day floor cycle speed.", icon: Building2 },
      { title: "Deep Secant Shoring", desc: "4-level deep basement retention with contiguous secant piles.", icon: Compass },
      { title: "Double-Glazed Envelope", desc: "Unitized Low-E curtain wall panels with acoustic and solar control.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Secant Piling & Basement Dig", desc: "Installing 600mm secant piles and pre-stressed ground tieback anchors." },
      { step: "02", title: "Mass Raft Concrete Pour", desc: "Continuous 72-hour chilled concrete pour for 3.5m thick raft foundation." },
      { step: "03", title: "Climbing Core & PT Floors", desc: "Rapid vertical construction using automated hydraulic climbing forms." },
      { step: "04", title: "Curtain Wall & MEP Fitout", desc: "Unitized facade installation, destination dispatch elevators, and BMS." },
    ],
    faqs: [
      { q: "What seismic design standards were applied to Apex Towers?", a: "Designed under UBC-97 and BCP for Seismic Zone 2B/3 with full ductile non-linear time-history verification." },
      { q: "How was groundwater handled during basement excavation?", a: "Deep well point dewatering and impermeable bentonite secant pile walls ensured completely dry excavation." },
    ],
  },
  {
    id: "mega-industrial-manufacturing-plant",
    slug: "mega-industrial-manufacturing-plant",
    title: "Automated Industrial Manufacturing Plant & PEB Complex",
    name: "Automated Industrial Manufacturing Plant & PEB Complex",
    category: "Industrial & Energy",
    tag: "Industrial & Energy",
    eyebrow: "Turnkey EPC Industrial Facility",
    location: "Sundar Industrial Estate, Punjab",
    client: "International FMCG & Industrial Group",
    value: "PKR 9.2 Billion",
    completionYear: "2024",
    image: "/images/walton/project_03_industrial.jpg",
    heroImage: "/images/walton/project_03_industrial.jpg",
    images: [
      "/images/walton/project_03_industrial.jpg",
      "/images/walton/solution_08_industrial.jpg",
      "/images/walton/service_03_construction_mgmt.jpg",
    ],
    summary:
      "Turnkey EPC construction of a 450,000 sq ft heavy industrial manufacturing facility. Scope included dynamic vibration-isolated machine foundations, 36m clear-span structural steel portal frames, a 132kV dedicated substation, and integrated effluent treatment.",
    overview:
      "Turnkey EPC construction of a 450,000 sq ft heavy industrial manufacturing facility. Scope included dynamic vibration-isolated machine foundations, 36m clear-span structural steel portal frames, a 132kV dedicated substation, and integrated effluent treatment.",
    scope: [
      "450,000 sq ft clear-span pre-engineered structural steel portal building with standing seam metal roofing",
      "Specialized heavy dynamic foundation slabs isolated with elastomeric damping pads for stamping presses",
      "Dedicated 132kV grid connection substation, motor control centers (MCC), and SCADA power distribution",
      "Industrial biological Effluent Treatment Plant (ETP) capable of processing 500,000 gallons per day",
    ],
    deliverables: [
      "450,000 sq ft clear-span pre-engineered structural steel portal building with standing seam metal roofing",
      "Specialized heavy dynamic foundation slabs isolated with elastomeric damping pads for stamping presses",
      "Dedicated 132kV grid connection substation, motor control centers (MCC), and SCADA power distribution",
      "Industrial biological Effluent Treatment Plant (ETP) capable of processing 500,000 gallons per day",
    ],
    technicalSpecs: [
      { key: "Covered Floor Space", value: "450,000 sq ft clear-span industrial area" },
      { key: "Structural Steel Frame", value: "High-yield ASTM A572 Grade-50 steel portal frames" },
      { key: "Electrical Substation", value: "132/11 kV outdoor grid substation with GIS switchgear" },
      { key: "Environmental ETP", value: "Biological activated sludge wastewater treatment plant" },
    ],
    metrics: [
      { label: "Covered Area", value: "450,000 sq ft" },
      { label: "Clear Span", value: "36 Meters" },
      { label: "Power Substation", value: "132/11 kV" },
      { label: "Turnkey EPC", value: "14 Months" },
    ],
    pillars: [
      { title: "36m Clear-Span PEB", desc: "Column-free industrial layout optimizing production lines.", icon: Building2 },
      { title: "Dynamic Vibration Isolation", desc: "Elastomeric damper pads isolating stamping presses from facility slab.", icon: Compass },
      { title: "132kV Substation", desc: "Turnkey industrial power substation ensuring uninterrupted electrical supply.", icon: Award },
      { title: "Effluent Treatment Plant", desc: "Closed-loop ETP recycling wastewater for cooling and irrigation.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "FEED & Dynamic Modeling", desc: "Finite element modeling of machine loads and process layout." },
      { step: "02", title: "Civil Works & Machine Beds", desc: "Heavy reinforced machine foundation pit casting and floor slabs." },
      { step: "03", title: "Structural Steel Erection", desc: "Rigging 36m clear-span portal frames and roof cladding." },
      { step: "04", title: "Substation & Commissioning", desc: "Substation energization, trial batch runs, and client handover." },
    ],
    faqs: [
      { q: "What turnaround time was achieved for this plant?", a: "The entire facility was delivered in 14 months from greenfield to trial production run." },
      { q: "Did Walton manage the machinery installation?", a: "Yes, our certified heavy rigging teams positioned all production machinery." },
    ],
  },
  {
    id: "indus-river-cable-stayed-bridge",
    slug: "indus-river-cable-stayed-bridge",
    title: "Indus River Multilane Highway Bridge & Expressway",
    name: "Indus River Multilane Highway Bridge & Expressway",
    category: "Highways & Bridges",
    tag: "Highways & Bridges",
    eyebrow: "River Crossing Infrastructure",
    location: "Khyber Pakhtunkhwa / Punjab Border",
    client: "Ministry of Communications / Federal Infrastructure",
    value: "PKR 22.4 Billion",
    completionYear: "2026",
    image: "/images/walton/project_04_transport.jpg",
    heroImage: "/images/walton/project_04_transport.jpg",
    images: [
      "/images/walton/project_04_transport.jpg",
      "/images/walton/hero_transportation.jpg",
      "/images/walton/hero_infrastructure.jpg",
    ],
    summary:
      "A high-profile 2.4-kilometer highway bridge crossing over the Indus River with high-pier pylons, prestressed concrete box girders, and high-velocity scour protection designed to endure extreme flood events.",
    overview:
      "A high-profile 2.4-kilometer highway bridge crossing over the Indus River with high-pier pylons, prestressed concrete box girders, and high-velocity scour protection designed to endure extreme flood events.",
    scope: [
      "2,400m bridge superstructure featuring twin 60m main navigation spans and 38 approach spans",
      "Rotary bored cast-in-place concrete foundation piles drilled 48 meters deep into bedrock",
      "Hydraulic bridge piers with hydrodynamic bullet-nose geometry for scouring prevention",
      "Approach embankments stabilized with reinforced earth (RE) walls and woven geotextiles",
    ],
    deliverables: [
      "2,400m bridge superstructure featuring twin 60m main navigation spans and 38 approach spans",
      "Rotary bored cast-in-place concrete foundation piles drilled 48 meters deep into bedrock",
      "Hydraulic bridge piers with hydrodynamic bullet-nose geometry for scouring prevention",
      "Approach embankments stabilized with reinforced earth (RE) walls and woven geotextiles",
    ],
    technicalSpecs: [
      { key: "Total Length", value: "2,400 meters (2.4 km) multi-lane bridge structure" },
      { key: "Piling Depth", value: "48 meters deep cast-in-place foundation piles" },
      { key: "Hydraulic Standard", value: "Designed for 100-year peak flood velocity of 4.8 m/s" },
      { key: "Superstructure Type", value: "Segmental post-tensioned concrete box girder" },
    ],
    metrics: [
      { label: "Bridge Length", value: "2,400 m" },
      { label: "Foundation Depth", value: "48 m" },
      { label: "Design Flood Return", value: "100-Year Peak" },
      { label: "Traffic Lanes", value: "6 Lanes" },
    ],
    pillars: [
      { title: "Segmental Box Girders", desc: "Long 60m clear spans over river navigation channels.", icon: Layers },
      { title: "Hydrodynamic Piers", desc: "Bullet-nosed pier geometry preventing hydraulic vortex scouring.", icon: Compass },
      { title: "Reinforced Earth Embankments", desc: "Geotextile-stabilized approach ramps resisting erosion.", icon: Truck },
      { title: "Seismic Elastomeric Bearings", desc: "High-damping rubber bearings isolating ground earthquake shock.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Bathymetric & Subsea Drilling", desc: "Riverbed sonar bathymetry and core sample drilling from barges." },
      { step: "02", title: "Cofferdam & Deep Piling", desc: "Sheet pile cofferdams and 48m rotary bored foundation piling." },
      { step: "03", title: "Pier Casting & Girder Launch", desc: "Casting reinforced piers and launching post-tensioned box girders." },
      { step: "04", title: "Deck Paving & Testing", desc: "Dynamic load test with 40-ton test trucks, asphalt paving, and opening." },
    ],
    faqs: [
      { q: "How deep into the riverbed do the bridge piles extend?", a: "Piles extend 48 meters into solid bedrock anchored through polymer drilling muds." },
      { q: "What traffic load capacity does the bridge support?", a: "Engineered to AASHTO HL-93 truck loading for unrestricted heavy multi-axle freight." },
    ],
  },
  {
    id: "grid-scale-renewable-energy-substation",
    slug: "grid-scale-renewable-energy-substation",
    title: "150 MW Solar Utility Park & Transmission Infrastructure",
    name: "150 MW Solar Utility Park & Transmission Infrastructure",
    category: "Industrial & Energy",
    tag: "Industrial & Energy",
    eyebrow: "Utility-Scale Renewable Infrastructure",
    location: "Quaid-e-Azam Solar Park, Bahawalpur",
    client: "Energy Department / Private Independent Power Producer (IPP)",
    value: "PKR 12.6 Billion",
    completionYear: "2025",
    image: "/images/walton/project_05_energy.jpg",
    heroImage: "/images/walton/project_05_energy.jpg",
    images: [
      "/images/walton/project_05_energy.jpg",
      "/images/walton/solution_06_sustainable.jpg",
      "/images/walton/hero_sustainable_infra.jpg",
    ],
    summary:
      "Engineering, civil foundation construction, and electrical balance of plant (BOP) for a 150 MW utility-scale solar photovoltaic facility with 220kV transmission substation and switchyard.",
    overview:
      "Engineering, civil foundation construction, and electrical balance of plant (BOP) for a 150 MW utility-scale solar photovoltaic facility with 220kV transmission substation and switchyard.",
    scope: [
      "Civil grading, access roads, and pile ramming for 320,000 bifacial solar tracker modules",
      "Construction of 220/33kV central power substation control building and transformer blast-walls",
      "Installation of 45 kilometers of underground medium-voltage (MV) feeder cabling networks",
      "SCADA control center with fiber-optic telemetry linked directly to national load dispatch center",
    ],
    deliverables: [
      "Civil grading, access roads, and pile ramming for 320,000 bifacial solar tracker modules",
      "Construction of 220/33kV central power substation control building and transformer blast-walls",
      "Installation of 45 kilometers of underground medium-voltage (MV) feeder cabling networks",
      "SCADA control center with fiber-optic telemetry linked directly to national load dispatch center",
    ],
    technicalSpecs: [
      { key: "Generation Capacity", value: "150 MWdc peak power generation" },
      { key: "Substation Voltage", value: "220 kV / 33 kV grid synchronization" },
      { key: "Modules Deployed", value: "320,000 bifacial tier-1 photovoltaic panels with single-axis tracking" },
      { key: "Cabling Network", value: "45 km underground MV feeder cables with fiber telemetry" },
    ],
    metrics: [
      { label: "Peak Generation", value: "150 MW" },
      { label: "Substation Voltage", value: "220/33 kV" },
      { label: "CO₂ Displaced", value: "190K Tons/yr" },
      { label: "Clean Homes Lit", value: "120,000+" },
    ],
    pillars: [
      { title: "Bifacial Solar Trackers", desc: "Single-axis trackers maximizing energy yield in high-irradiance desert zones.", icon: Layers },
      { title: "220kV Grid Substation", desc: "Central high-voltage substation with automated SF6 gas insulated switchgear.", icon: Award },
      { title: "Underground MV Feeders", desc: "Heavy-duty armored cable networks buried to prevent heat degradation.", icon: Compass },
      { title: "National SCADA Sync", desc: "Real-time automated telemetry synchronized with the National Transmission Grid.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Terrain Grading & Pile Ramming", desc: "Precision civil grading and ramming 80,000 galvanized steel tracker posts." },
      { step: "02", title: "Tracker & Module Assembly", desc: "Mounting single-axis automated trackers and bifacial PV modules." },
      { step: "03", title: "Substation Civil & Electrical", desc: "Constructing transformer foundations, blast walls, and switchyard." },
      { step: "04", title: "Grid Sync & Performance Testing", desc: "Cold/hot testing and synchronizing clean power into the national grid." },
    ],
    faqs: [
      { q: "How much carbon dioxide does this solar facility offset?", a: "It displaces approximately 190,000 tons of CO₂ emissions each year." },
      { q: "What was Walton's exact scope?", a: "Turnkey civil engineering, pile foundations, access roads, 220kV substation construction, and MV cable installation." },
    ],
  },
  {
    id: "islamabad-metropolitan-civic-center",
    slug: "islamabad-metropolitan-civic-center",
    title: "Capital Metropolitan Commercial Plaza & Tech Campus",
    name: "Capital Metropolitan Commercial Plaza & Tech Campus",
    category: "Commercial & Urban",
    tag: "Commercial & Urban",
    eyebrow: "Smart Commercial Campus",
    location: "Blue Area Extension, Islamabad",
    client: "Capital Development Authority & Private Developers",
    value: "PKR 16.2 Billion",
    completionYear: "2025",
    image: "/images/walton/project_06_urban.jpg",
    heroImage: "/images/walton/project_06_urban.jpg",
    images: [
      "/images/walton/project_06_urban.jpg",
      "/images/walton/solution_03_urban.jpg",
      "/images/walton/hero_modern_architecture.jpg",
    ],
    summary:
      "A state-of-the-art 24-storey institutional and commercial center featuring smart building automation, landscaped public amphitheater, green roof terraces, and integrated multi-modal transit access.",
    overview:
      "A state-of-the-art 24-storey institutional and commercial center featuring smart building automation, landscaped public amphitheater, green roof terraces, and integrated multi-modal transit access.",
    scope: [
      "High-rise composite steel-concrete ductile frame engineered for Seismic Zone 2B/3 criteria",
      "Architectural terracotta ventilated rain-screen facade with automated exterior solar louvers",
      "Public landscaped civic plaza featuring indigenous drought-resistant greenery and water features",
      "Central building management system (BMS) optimizing HVAC and daylight illumination",
    ],
    deliverables: [
      "High-rise composite steel-concrete ductile frame engineered for Seismic Zone 2B/3 criteria",
      "Architectural terracotta ventilated rain-screen facade with automated exterior solar louvers",
      "Public landscaped civic plaza featuring indigenous drought-resistant greenery and water features",
      "Central building management system (BMS) optimizing HVAC and daylight illumination",
    ],
    technicalSpecs: [
      { key: "Total Area", value: "980,000 sq ft gross floor area" },
      { key: "Building Height", value: "105 meters (24 storeys above grade)" },
      { key: "Facade Technology", value: "Ventilated terracotta rain-screen + motorized solar louvers" },
      { key: "Energy Rating", value: "28% energy reduction vs. ASHRAE baseline" },
    ],
    metrics: [
      { label: "Gross Floor Area", value: "980,000 sq ft" },
      { label: "Height", value: "105 Meters" },
      { label: "Public Realm", value: "4.5 Acres" },
      { label: "Energy Savings", value: "28% vs Baseline" },
    ],
    pillars: [
      { title: "Terracotta Rain-Screen", desc: "Energy-efficient architectural ventilated facade reducing HVAC cooling load.", icon: Building2 },
      { title: "Smart Building BMS", desc: "Automated controls optimizing chiller loops, ventilation, and daylighting.", icon: Compass },
      { title: "Civic Public Realm", desc: "4.5 acres of pedestrian plazas, open amphitheaters, and indigenous flora.", icon: Layers },
      { title: "Seismic Resilience", desc: "Composite ductile frame designed for strict capital seismic guidelines.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Boring & Mat Foundation", desc: "Excavation and mass concrete foundation casting in Blue Area." },
      { step: "02", title: "Superstructure Frame Build", desc: "Composite concrete-steel structural floor casting." },
      { step: "03", title: "Architectural Rain-Screen Facade", desc: "Installing terracotta rain-screen panels and motorized solar louvers." },
      { step: "04", title: "Public Plaza & Commissioning", desc: "Civic landscaping, fountain installation, and smart BMS integration." },
    ],
    faqs: [
      { q: "What green building features are integrated?", a: "Terracotta rain-screen facades, green rooftop terraces, LED smart sensors, and rainwater harvesting." },
      { q: "Is public access integrated into the development?", a: "Yes, 4.5 acres of landscaped civic plazas connect directly to the metro transit bus corridor." },
    ],
  },
  {
    id: "metropolitan-water-treatment-canal-aqueduct",
    slug: "metropolitan-water-treatment-canal-aqueduct",
    title: "Urban Water Treatment Works & Regional Conveyance Canal",
    name: "Urban Water Treatment Works & Regional Conveyance Canal",
    category: "Sustainable & Water",
    tag: "Sustainable & Water",
    eyebrow: "Water Utility & Environmental Works",
    location: "Faisalabad Industrial City (M-3 Corridor)",
    client: "Water and Sanitation Agency (WASA) / FIEDMC",
    value: "PKR 8.8 Billion",
    completionYear: "2024",
    image: "/images/walton/project_07_water.jpg",
    heroImage: "/images/walton/project_07_water.jpg",
    images: [
      "/images/walton/project_07_water.jpg",
      "/images/walton/hero_sustainable_infra.jpg",
      "/images/walton/service_04_infrastructure.jpg",
    ],
    summary:
      "Comprehensive municipal water infrastructure including a 50 MGD water treatment facility, 18 kilometers of ductile iron water transmission mains, reinforced concrete balancing reservoirs, and elevated storage towers.",
    overview:
      "Comprehensive municipal water infrastructure including a 50 MGD water treatment facility, 18 kilometers of ductile iron water transmission mains, reinforced concrete balancing reservoirs, and elevated storage towers.",
    scope: [
      "50 Million Gallons per Day (MGD) rapid sand filtration and chlorine contact clarifier basins",
      "Post-tensioned circular concrete reservoir tanks with food-grade epoxy protective lining",
      "18km 1200mm diameter ductile iron pipeline installed with trenchless micro-tunneling under highways",
      "Solar-assisted high-lift pumping station delivering treated water across 4 municipal zones",
    ],
    deliverables: [
      "50 Million Gallons per Day (MGD) rapid sand filtration and chlorine contact clarifier basins",
      "Post-tensioned circular concrete reservoir tanks with food-grade epoxy protective lining",
      "18km 1200mm diameter ductile iron pipeline installed with trenchless micro-tunneling under highways",
      "Solar-assisted high-lift pumping station delivering treated water across 4 municipal zones",
    ],
    technicalSpecs: [
      { key: "Treatment Capacity", value: "50 Million Gallons per Day (MGD)" },
      { key: "Conveyance Pipeline", value: "18 km of 1200mm diameter ductile iron Class K9 pipe" },
      { key: "Trenchless Technology", value: "Micro-tunneling pipe jacking under motorways and railways" },
      { key: "Water Standard", value: "Meets 100% WHO and National Drinking Water Quality Standards" },
    ],
    metrics: [
      { label: "Treatment Capacity", value: "50 MGD" },
      { label: "Conveyance Main", value: "18 km" },
      { label: "Water Purity", value: "WHO Standard" },
      { label: "Beneficiary Pop", value: "850,000 Citizens" },
    ],
    pillars: [
      { title: "Rapid Sand Clarifiers", desc: "Automated multi-stage clarification basins purifying canal water.", icon: Layers },
      { title: "Trenchless Micro-Tunneling", desc: "Pipe jacking beneath busy motorways with zero traffic disruption.", icon: Compass },
      { title: "Post-Tensioned Reservoirs", desc: "Circular concrete water reservoirs lined with food-grade epoxy.", icon: Building2 },
      { title: "Solar-Assisted Pumping", desc: "Energy-efficient pumps backed by rooftop solar reducing operational costs.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Hydraulic Sizing & Intake Design", desc: "Canal intake structure and gravity conveyance hydraulic modeling." },
      { step: "02", title: "Treatment Basin Civil Casting", desc: "Casting clarifiers, filtration beds, and post-tensioned reservoir tanks." },
      { step: "03", title: "Pipeline Trenchless Jacking", desc: "Micro-tunneling 1200mm water mains beneath highway crossings." },
      { step: "04", title: "Pumps & Water Quality Testing", desc: "Full hydrostatic pressure tests, disinfection, and commissioning." },
    ],
    faqs: [
      { q: "What population does this water project serve?", a: "It provides clean WHO-standard drinking water to over 850,000 citizens and industrial units." },
      { q: "How was highway crossing executed?", a: "We deployed laser-guided micro-tunneling pipe jacking without excavating the motorway surface." },
    ],
  },
  {
    id: "green-transit-eco-corridor",
    slug: "green-transit-eco-corridor",
    title: "Smart Eco-Corridor & Sustainable Urban Transitway",
    name: "Smart Eco-Corridor & Sustainable Urban Transitway",
    category: "Sustainable & Water",
    tag: "Sustainable & Water",
    eyebrow: "Green Transportation Infrastructure",
    location: "Rawalpindi – Islamabad Ring Expressway",
    client: "RDA / Provincial Sustainable Transport Board",
    value: "PKR 11.5 Billion",
    completionYear: "2026",
    image: "/images/walton/project_08_sustainable.jpg",
    heroImage: "/images/walton/project_08_sustainable.jpg",
    images: [
      "/images/walton/project_08_sustainable.jpg",
      "/images/walton/hero_sustainable_infra.jpg",
      "/images/walton/solution_07_transport.jpg",
    ],
    summary:
      "Pioneering sustainable civil corridor combining dedicated electric transit lanes, solar-canopied charging stations, bioswales for rainwater retention, and smart LED streetlighting networks.",
    overview:
      "Pioneering sustainable civil corridor combining dedicated electric transit lanes, solar-canopied charging stations, bioswales for rainwater retention, and smart LED streetlighting networks.",
    scope: [
      "32-kilometer green expressway median with automated drip-irrigated afforestation belts",
      "Dedicated grade-separated lanes for electric transit fleets with integrated inductive recharge bays",
      "Permeable pavement parking facilities and engineered bioswales recharging local aquifers",
      "Solar photovoltaic acoustic noise barrier panels generating 4.2 MW clean electricity",
    ],
    deliverables: [
      "32-kilometer green expressway median with automated drip-irrigated afforestation belts",
      "Dedicated grade-separated lanes for electric transit fleets with integrated inductive recharge bays",
      "Permeable pavement parking facilities and engineered bioswales recharging local aquifers",
      "Solar photovoltaic acoustic noise barrier panels generating 4.2 MW clean electricity",
    ],
    technicalSpecs: [
      { key: "Corridor Route", value: "32 kilometers dedicated eco-transitway" },
      { key: "Solar Noise Barriers", value: "4.2 MW integrated photovoltaic acoustic panels" },
      { key: "Water Conservation", value: "Engineered bioswales infiltrating 1.2M m³ rainwater annually" },
      { key: "Transit Capacity", value: "80,000 electric bus passengers daily" },
    ],
    metrics: [
      { label: "Corridor Route", value: "32 km" },
      { label: "Clean Solar Yield", value: "4.2 MW" },
      { label: "Water Infiltrated", value: "1.2M m³/yr" },
      { label: "Transit Capacity", value: "80K Passengers/day" },
    ],
    pillars: [
      { title: "Solar Noise Barriers", desc: "Acoustic barriers generating 4.2 MW electricity while attenuating sound.", icon: Layers },
      { title: "Aquifer Bioswales", desc: "Engineered natural swales capturing and filtering highway rainwater runoff.", icon: Compass },
      { title: "Dedicated EV Transit", desc: "Grade-separated lanes for zero-emission electric bus rapid transit.", icon: Truck },
      { title: "Smart LED Network", desc: "Motion-sensing solar LED lights minimizing energy consumption.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Eco-Corridor Geometric Design", desc: "Aligning dedicated transit lanes alongside green drainage medians." },
      { step: "02", title: "Earthworks & Bioswale Shoring", desc: "Grading retention bioswales and placing permeable filter strata." },
      { step: "03", title: "Solar Barrier Installation", desc: "Erecting structural steel posts and mounting photovoltaic acoustic panels." },
      { step: "04", title: "Transit Lane Opening", desc: "Paving high-durability busway lanes and testing electric fleet bays." },
    ],
    faqs: [
      { q: "How much clean power do the solar noise barriers produce?", a: "The 4.2 MW solar barrier produces enough electricity to power all corridor streetlights and EV charging stations." },
      { q: "What is the benefit of the permeable pavement bioswales?", a: "They capture 1.2 million cubic meters of monsoon runoff each year, recharging the local drinking water aquifer." },
    ],
  },
];

export function getWaltonProjectBySlug(slug) {
  if (!slug) return null;
  return (
    WALTON_PROJECTS.find(
      (p) =>
        p.slug === slug ||
        p.id === slug ||
        p.slug.replace(/-/g, "") === slug.replace(/-/g, "")
    ) || null
  );
}
