// Comprehensive Civil Engineering & Infrastructure Services Dataset for Walton Consultants & Contracting
import {
  Building2,
  Hammer,
  Truck,
  Layers,
  Wrench,
  ClipboardList,
  ShieldCheck,
  Award,
  Scale,
  Compass,
  FileCheck2,
  Calculator,
  HardHat,
  Users2,
  FileSpreadsheet,
  Zap,
  Activity,
  CheckCircle2,
} from "lucide-react";

export const WALTON_SERVICES = [
  {
    id: "engineering-consultancy",
    slug: "engineering-consultancy",
    title: "Engineering Consultancy",
    subtitle: "Structural Design, Civil Engineering & Technical Oversight",
    eyebrow: "Structural Engineering & Advisory",
    category: "Technical Advisory",
    tag: "Engineering Consultancy",
    icon: Compass,
    image: "/images/walton/service_01_consultancy.jpg",
    heroImage: "/images/walton/service_01_consultancy.jpg",
    images: [
      "/images/walton/service_01_consultancy.jpg",
      "/images/walton/about_conference_plans.jpg",
      "/images/walton/hero_engineering_team.jpg",
    ],
    overview:
      "Walton provides multidisciplinary engineering consultancy across structural design, geotechnical engineering, foundation analysis, and civil systems. Backed by PEC C-A (No Limit) licensing, our engineers provide peer reviews, seismic hazard assessments, and finite-element modeling to ensure lasting structural integrity.",
    metrics: [
      { label: "Consulting Projects", value: "450+" },
      { label: "Seismic Codes", value: "BCP / ACI 318" },
      { label: "BIM Integration", value: "Level 2 / 3" },
      { label: "Satisfaction Rate", value: "99.4%" },
    ],
    deliverables: [
      "3D structural modeling and finite-element stress analysis (ETABS / SAFE / SAP2000)",
      "Comprehensive geotechnical soil investigation reviews and deep foundation designs",
      "Seismic hazard microzonation and dynamic response spectra calculations",
      "Structural peer review, value engineering, and material optimization reports",
      "MEP building services engineering and utility coordination",
      "Full compliance certification with Pakistan Building Code and international ASTM standards",
    ],
    technicalSpecs: [
      { key: "Governing Codes", value: "ACI 318-19, ASCE 7-16, UBC-97, Building Code of Pakistan (BCP)" },
      { key: "Analysis Software", value: "ETABS Ultimate, SAFE, CSI Bridge, Revit BIM, AutoCAD" },
      { key: "Foundation Scope", value: "Deep bored piles, secant walls, mat foundations, ground anchors" },
      { key: "Deliverable Formats", value: "Autodesk Revit BIM Models, IFC files, CAD sheets, stamped calculations" },
    ],
    pillars: [
      { title: "Seismic Resilient Design", desc: "Dual ductile shear wall cores engineered to withstand intense dynamic earthquake accelerations.", icon: ShieldCheck },
      { title: "3D BIM Coordination", desc: "Clash-free multi-discipline Building Information Models in Revit and Navisworks.", icon: Layers },
      { title: "Geotechnical Precision", desc: "Deep borehole profiling and soil stabilization for maximum foundation bearing capacity.", icon: Compass },
      { title: "Value Engineering", desc: "Material schedule optimization reducing concrete and rebar tonnage without compromising safety.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Site & Soil Geotechnical Assay", desc: "Performing core soil boring, plate load bearing tests, and seismic hazard analysis." },
      { step: "02", title: "Structural Analysis & Modeling", desc: "Simulating dynamic wind and seismic loads in ETABS and SAFE." },
      { step: "03", title: "Detailed Engineering Drawings", desc: "Drafting complete rebar bending schedules, connection details, and MEP sleeves." },
      { step: "04", title: "Peer Review & Statutory Approval", desc: "Securing municipal approvals and third-party engineering vetting." },
    ],
    faqs: [
      { q: "What design codes does Walton adhere to for structural calculations?", a: "We design strictly in accordance with the Building Code of Pakistan (BCP), ACI 318-19 for reinforced concrete, and AISC 360 for structural steel." },
      { q: "Can Walton perform independent structural peer reviews?", a: "Yes. As a PEC Category C-A firm, we regularly audit external engineering designs for safety compliance and material optimization." },
      { q: "Do you provide Building Information Modeling (BIM) services?", a: "Yes, we build 3D BIM models up to LOD 400 with full clash detection across architectural, structural, and MEP disciplines." },
    ],
  },
  {
    id: "project-management",
    slug: "project-management",
    title: "Project Management",
    subtitle: "Turnkey Project Oversight, Milestone Tracking & Resource Optimization",
    eyebrow: "Full Lifecycle Project Leadership",
    category: "Management & Governance",
    tag: "Project Management",
    icon: ClipboardList,
    image: "/images/walton/service_02_project_mgmt.jpg",
    heroImage: "/images/walton/service_02_project_mgmt.jpg",
    images: [
      "/images/walton/service_02_project_mgmt.jpg",
      "/images/walton/hero_engineering_team.jpg",
      "/images/walton/service_01_consultancy.jpg",
    ],
    overview:
      "Our project management teams apply Primavera P6 critical path scheduling, earned value analysis, and proactive risk management to safeguard budgets, quality benchmarks, and project handover dates. We act as client representative across design, procurement, and field construction.",
    metrics: [
      { label: "On-Time Handover", value: "98.8%" },
      { label: "Value Managed", value: "$450M+" },
      { label: "Methodology", value: "PMI / FIDIC" },
      { label: "Quality Pass", value: "100%" },
    ],
    deliverables: [
      "Detailed project execution plans (PEP) and work breakdown structures (WBS)",
      "Primavera P6 baseline schedules with critical path method (CPM) tracking",
      "Monthly earned value management (EVM) cost and progress forecasting",
      "Multi-stakeholder site coordination meetings and executive reporting dashboards",
      "Comprehensive site safety (HSE) oversight and zero-harm policy enforcement",
      "Substantial completion verification, punch-list clearance, and final handover",
    ],
    technicalSpecs: [
      { key: "Management Standards", value: "PMI PMBOK 7th Edition, FIDIC Red / Yellow / Silver Books" },
      { key: "Scheduling Tools", value: "Primavera P6 Professional, Microsoft Project Enterprise" },
      { key: "HSE Standards", value: "ISO 45001 Occupational Health and Safety Management" },
      { key: "Reporting", value: "Live cloud-based dashboards, drone inspection logs, BIM 4D schedules" },
    ],
    pillars: [
      { title: "Critical Path Scheduling", desc: "Milestone-driven Primavera P6 schedules tracking critical dependencies and equipment delivery.", icon: ClipboardList },
      { title: "Cost & Budget Control", desc: "Earned value management (EVM) preventing unexpected capital cost overruns.", icon: Calculator },
      { title: "HSE Zero-Harm Policy", desc: "Strict site safety induction, risk assessments, and continuous ISO 45001 auditing.", icon: ShieldCheck },
      { title: "Stakeholder Alignment", desc: "Transparent progress reports, live telemetry dashboards, and weekly technical briefings.", icon: Users2 },
    ],
    workflow: [
      { step: "01", title: "Baseline Setup & WBS Definition", desc: "Establishing the project charter, milestone schedules, and resource allocations." },
      { step: "02", title: "Procurement & Site Mobilization", desc: "Prequalifying subcontractors and synchronizing plant mobilization." },
      { step: "03", title: "Execution Tracking & Quality Audits", desc: "Daily field inspections, progress tracking, and material compliance verification." },
      { step: "04", title: "Commissioning & Closeout", desc: "Punch-list verification, as-built documentation, and formal client handover." },
    ],
    faqs: [
      { q: "How do you track construction schedule variance?", a: "We utilize Primavera P6 critical path schedules updated weekly with earned value metrics (SPI and CPI) to catch bottlenecks early." },
      { q: "What contract forms do you manage?", a: "We are experienced with the full FIDIC suite (Red, Yellow, Silver Books) and PEC Standard Bidding Documents." },
      { q: "Does Walton oversee on-site health and safety?", a: "Yes, our certified safety officers enforce rigorous ISO 45001 protocols on all operating jobsites." },
    ],
  },
  {
    id: "construction-management",
    slug: "construction-management",
    title: "Construction Management",
    subtitle: "On-Site Supervision, Structural Steel & Reinforced Concrete Works",
    eyebrow: "Field Execution Excellence",
    category: "Site Operations",
    tag: "Construction Management",
    icon: HardHat,
    image: "/images/walton/service_03_construction_mgmt.jpg",
    heroImage: "/images/walton/service_03_construction_mgmt.jpg",
    images: [
      "/images/walton/service_03_construction_mgmt.jpg",
      "/images/walton/hero_infrastructure.jpg",
      "/images/walton/solution_02_construction.jpg",
    ],
    overview:
      "Walton's construction management division supervises complex physical builds with precision. From multi-crane logistics and heavy structural steel erection to high-volume ready-mix pours and MEP coordination, our field engineers enforce uncompromising standards at every stage.",
    metrics: [
      { label: "Delivered Facilities", value: "350+" },
      { label: "Heavy Crane Fleet", value: "Up to 250T" },
      { label: "Safe Work Hours", value: "12M+ LTI-Free" },
      { label: "Concrete Placed", value: "2.5M+ m³" },
    ],
    deliverables: [
      "Direct on-site structural engineering supervision and daily inspection logs",
      "Heavy equipment mobilization, tower crane rigging, and logistics management",
      "Non-destructive testing (NDT) and concrete cylinder compressive strength testing",
      "Quality assurance audits covering rebar placements, formwork, and curing regimens",
      "Contractor performance scoring and site milestone certification",
      "Commissioning of MEP systems, fire suppressions, and building management networks",
    ],
    technicalSpecs: [
      { key: "QA/QC Protocol", value: "ASTM C39 (Concrete), AWS D1.1 (Structural Welding), ACI 301" },
      { key: "Heavy Plant", value: "Liebherr / Potain tower cranes, Putzmeister concrete boom pumps" },
      { key: "Formwork Systems", value: "Doka hydraulic climbing forms, Peri modular table forms" },
      { key: "Safety Record", value: "Zero fatal incidents across 25+ operating years" },
    ],
    pillars: [
      { title: "Heavy Rigging Logistics", desc: "Certified crane operations executing tandem lifts for multi-ton girders and steel trusses.", icon: Truck },
      { title: "Automated Concrete Quality", desc: "Temperature-monitored mass concrete batching ensuring crack-free high-strength curing.", icon: Building2 },
      { title: "Non-Destructive Testing", desc: "Ultrasonic weld inspection and rebound hammer testing verifying structural integrity.", icon: ShieldCheck },
      { title: "MEP Coordination", desc: "Flawless integration of electrical substations, plumbing manifolds, and HVAC ducts.", icon: Wrench },
    ],
    workflow: [
      { step: "01", title: "Substructure & Excavation", desc: "Rotary bored piling, contiguous retaining walls, and mass raft concrete pours." },
      { step: "02", title: "Superstructure Frame Build", desc: "Hydraulic self-climbing core forms and structural steel erection." },
      { step: "03", title: "Building Envelope & Facades", desc: "Unitized curtain wall installation, masonry, and architectural cladding." },
      { step: "04", title: "Testing & Systems Commissioning", desc: "Hydrostatic pipe tests, electrical load bank testing, and occupancy certification." },
    ],
    faqs: [
      { q: "What is Walton's equipment capacity for heavy lifts?", a: "We deploy mobile and crawler cranes up to 250 tons single-piece lifting capacity with certified rigging engineers." },
      { q: "How do you handle hot weather concrete pours in Pakistan?", a: "We use liquid nitrogen or flake ice water chillers, retarder admixtures, and night-pour protocols to prevent thermal cracking." },
      { q: "Can Walton manage specialized pre-engineered steel buildings (PEBs)?", a: "Yes, we have erected over 8.5 million square feet of clear-span PEB steel facilities." },
    ],
  },
  {
    id: "infrastructure-development",
    slug: "infrastructure-development",
    title: "Infrastructure Development",
    subtitle: "Highways, Interchanges, Expressways & Municipal Utility Networks",
    eyebrow: "Large-Scale Civil Infrastructure",
    category: "Civil Works",
    tag: "Infrastructure Development",
    icon: Layers,
    image: "/images/walton/service_04_infrastructure.jpg",
    heroImage: "/images/walton/service_04_infrastructure.jpg",
    images: [
      "/images/walton/service_04_infrastructure.jpg",
      "/images/walton/hero_transportation.jpg",
      "/images/walton/solution_01_infrastructure.jpg",
    ],
    overview:
      "We design and build critical transportation corridors, multi-lane grade-separated interchanges, prestressed bridges, and stormwater culverts. Engineered to sustain intense freight transit and extreme climatic cycles, our infrastructure unlocks regional economic productivity.",
    metrics: [
      { label: "Highway Corridors", value: "650+ km" },
      { label: "Bridges & Overpasses", value: "48+" },
      { label: "Design Life", value: "100 Years" },
      { label: "Interchanges Built", value: "18+" },
    ],
    deliverables: [
      "Highway alignment geometry, digital terrain modeling, and mass-haul optimization",
      "Precast prestressed concrete I-girder and box-girder bridge construction",
      "Laser-guided asphalt paving, sub-base compaction, and drainage infrastructure",
      "High-capacity stormwater box culverts and canal crossing aqueducts",
      "Highway signage, intelligent traffic control loops, and high-mast LED illumination",
      "Comprehensive environmental mitigation and soil stabilization geotextiles",
    ],
    technicalSpecs: [
      { key: "Design Standards", value: "AASHTO LRFD Bridge Design, NHA Pakistan Specifications" },
      { key: "Paving Technology", value: "Vögele laser-controlled asphalt pavers, Hamm pneumatic rollers" },
      { key: "Asphalt Grade", value: "Superpave high-modulus polymer modified asphalt (PMA)" },
      { key: "Bridge Girders", value: "Post-tensioned segmental concrete box girders up to 60m span" },
    ],
    pillars: [
      { title: "Heavy Axle Load Durability", desc: "Road pavements designed to withstand severe overloading and extreme summer temperatures.", icon: Truck },
      { title: "Prestressed Bridge Engineering", desc: "Long-span precast box girders engineered for seismic resilience and flood scour protection.", icon: Layers },
      { title: "Laser-Guided Paving", desc: "Automated asphalt paving achieving international roughness index (IRI) benchmarks.", icon: Compass },
      { title: "Stormwater Management", desc: "Engineered box culverts and roadside drainage preventing road waterlogging.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Topographic Survey & Mass-Haul", desc: "LiDAR drone mapping and digital terrain cut-and-fill optimization." },
      { step: "02", title: "Sub-Base Compaction & Drainage", desc: "Granular sub-base placement, nuclear density testing, and culvert installation." },
      { step: "03", title: "Bridge Pier & Girder Launching", desc: "Hydraulic piling, pier cap casting, and post-tensioned girder launching." },
      { step: "04", title: "Asphalt Wearing Course & Signage", desc: "Paving polymer asphalt, guardrails, thermal road markings, and toll gantries." },
    ],
    faqs: [
      { q: "What standards govern Walton's bridge designs?", a: "We design according to AASHTO LRFD specifications and National Highway Authority (NHA) codes." },
      { q: "What asphalt mixes do you deploy on major expressways?", a: "We deploy polymer-modified bitumen (PMB) Superpave asphalt mixes formulated to resist rutting in 45°C+ summer heat." },
      { q: "Does Walton construct grade-separated cloverleaf interchanges?", a: "Yes, we have executed 18+ high-capacity flyovers and interchanges across major urban arteries." },
    ],
  },
  {
    id: "architecture-planning",
    slug: "architecture-planning",
    title: "Architecture & Planning",
    subtitle: "Master Planning, Commercial Design & Urban Spatial Development",
    eyebrow: "Master Planning & Design",
    category: "Design & Planning",
    tag: "Architecture & Planning",
    icon: Building2,
    image: "/images/walton/service_05_architecture.jpg",
    heroImage: "/images/walton/service_05_architecture.jpg",
    images: [
      "/images/walton/service_05_architecture.jpg",
      "/images/walton/hero_modern_architecture.jpg",
      "/images/walton/solution_03_urban.jpg",
    ],
    overview:
      "Walton's architects and master planners create functional, elegant, and sustainable environments. From mixed-use commercial districts and industrial zones to corporate headquarters, we integrate bioclimatic principles, pedestrian flows, and commercial viability.",
    metrics: [
      { label: "Master Plans Designed", value: "35+" },
      { label: "Total Planned Area", value: "12,000+ Acres" },
      { label: "Efficiency Gain", value: "22% Net-Leasable" },
      { label: "Green Certifications", value: "LEED Gold / Plat" },
    ],
    deliverables: [
      "Comprehensive urban master plans, zoning layouts, and circulation diagrams",
      "Architectural concept design, spatial optimization, and high-fidelity 3D renderings",
      "Building envelope design, curtain wall details, and acoustic insulation planning",
      "Landscape architecture, civic plazas, and water-sensitive public spaces",
      "Statutory municipal zoning submissions and building authority approval dossiers",
      "Interior spatial planning and high-efficiency circulation floor plates",
    ],
    technicalSpecs: [
      { key: "Design Tools", value: "Revit Architecture, Rhino 3D, Grasshopper, 3ds Max, Lumion" },
      { key: "Green Building", value: "USGBC LEED / EDGE Green Building Certification Standards" },
      { key: "Zoning Codes", value: "LDA / CDA / SBCA Building Bylaws and International Building Code (IBC)" },
      { key: "Acoustics & Lighting", value: "Dialux solar daylighting simulations, ASHRAE 90.1 compliance" },
    ],
    pillars: [
      { title: "Spatial Efficiency", desc: "Floor plans engineered to maximize usable leasable area and natural daylight illumination.", icon: Building2 },
      { title: "Bioclimatic Design", desc: "Passive solar orientation, natural ventilation corridors, and high-performance facades.", icon: Compass },
      { title: "Urban Integration", desc: "Seamless pedestrian boulevards, multi-modal transit links, and civic open spaces.", icon: Users2 },
      { title: "Regulatory Approvals", desc: "Flawless compliance with municipal zoning bylaws ensuring swift building permits.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Site Context & Feasibility", desc: "Topographic analysis, zoning constraints, and sun-path microclimate studies." },
      { step: "02", title: "Concept Massing & Master Plan", desc: "Developing 3D volumetric massing models, spatial layouts, and circulation routes." },
      { step: "03", title: "BIM Architectural Detailing", desc: "Detailed construction documentation, curtain wall specifications, and interior finishes." },
      { step: "04", title: "Authority Clearance & Tendering", desc: "Finalizing municipal approval dossiers and issuing comprehensive architectural tenders." },
    ],
    faqs: [
      { q: "What types of master planning does Walton undertake?", a: "We plan industrial estates, commercial business districts, high-rise campuses, and master-planned residential communities." },
      { q: "Do your architectural plans include sustainability benchmarks?", a: "Yes, our designs align with USGBC LEED guidelines, optimizing energy, water, and indoor environmental quality." },
      { q: "Can Walton handle building authority permit submissions?", a: "Yes, we prepare statutory drawings and documentation for LDA, CDA, SBCA, and local municipal corporations." },
    ],
  },
  {
    id: "feasibility-studies",
    slug: "feasibility-studies",
    title: "Feasibility & Technical Studies",
    subtitle: "Technical, Economic & Environmental Project Validation",
    eyebrow: "Pre-Development Analysis",
    category: "Strategic Advisory",
    tag: "Feasibility Studies",
    icon: FileCheck2,
    image: "/images/walton/service_06_feasibility.jpg",
    heroImage: "/images/walton/service_06_feasibility.jpg",
    images: [
      "/images/walton/service_06_feasibility.jpg",
      "/images/walton/about_conference_plans.jpg",
      "/images/walton/service_01_consultancy.jpg",
    ],
    overview:
      "Before breaking ground, Walton conducts exhaustive feasibility studies analyzing technical viability, geological risks, capital cost forecasts, economic returns, and statutory clearances to derisk high-capital infrastructure investments.",
    metrics: [
      { label: "Studies Executed", value: "280+" },
      { label: "Forecast Accuracy", value: "±3.5%" },
      { label: "Approved Funding", value: "$1.2B+" },
      { label: "Time-to-Approval", value: "-30% Faster" },
    ],
    deliverables: [
      "Topographic surveys, LiDAR aerial drone mapping, and geotechnical soil profiles",
      "Traffic volume modeling, origin-destination matrices, and pavement design life studies",
      "Environmental & Social Impact Assessments (ESIA) and EPA clearance reports",
      "Capital expenditure (CAPEX) modeling and lifecycle operational expense (OPEX) estimates",
      "Sensitivity risk modeling, financial internal rate of return (IRR), and debt service ratios",
      "Comprehensive bankable feasibility reports prepared for institutional lenders",
    ],
    technicalSpecs: [
      { key: "Survey Technology", value: "RTK GPS, Leica total stations, multi-rotor LiDAR survey drones" },
      { key: "Environmental", value: "EPA Pakistan Environmental Protection Act Guidelines, World Bank EHS" },
      { key: "Financial Modeling", value: "Monte Carlo risk simulations, discounted cash flow (DCF) models" },
      { key: "Report Standard", value: "Bankable feasibility format approved by domestic and multilateral banks" },
    ],
    pillars: [
      { title: "Bankable Accuracy", desc: "Rigorous financial forecasts approved by commercial banks and multilateral development funds.", icon: FileCheck2 },
      { title: "Geological Risk Elimination", desc: "Deep geotechnical boreholes and groundwater assays uncovering subterranean risks.", icon: Compass },
      { title: "Traffic & Demand Forecasting", desc: "Comprehensive traffic modeling calculating accurate highway and toll revenue potential.", icon: Truck },
      { title: "Environmental Clearance", desc: "Statutory Environmental Impact Assessments securing EPA approvals without delays.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Preliminary Site & Market Recon", desc: "Gathering baseline GIS data, traffic counts, and regulatory zoning frameworks." },
      { step: "02", title: "Field Surveys & Geotech Testing", desc: "Executing drone LiDAR mapping, geotechnical drilling, and socio-environmental surveys." },
      { step: "03", title: "Engineering Modeling & Costing", desc: "Formulating preliminary engineering designs, CAPEX estimates, and revenue projections." },
      { step: "04", title: "Bankable Report Finalization", desc: "Delivering institutional-grade bankable feasibility dossiers and executive presentations." },
    ],
    faqs: [
      { q: "Are Walton's feasibility studies accepted by international financing institutions?", a: "Yes, our reports adhere to World Bank, ADB, and international banking standards for infrastructure lending." },
      { q: "What survey tools do you use for terrain mapping?", a: "We utilize RTK GPS base stations, Leica total stations, and LiDAR-equipped drones producing sub-centimeter contour maps." },
      { q: "How long does a comprehensive feasibility study take?", a: "Depending on project scope, turnaround typically ranges from 4 to 12 weeks." },
    ],
  },
  {
    id: "quantity-surveying",
    slug: "quantity-surveying",
    title: "Quantity Surveying",
    subtitle: "Bill of Quantities (BOQ), Cost Planning & Material Audits",
    eyebrow: "Cost Certainty & Measurement",
    category: "Commercial Management",
    tag: "Quantity Surveying",
    icon: Calculator,
    image: "/images/walton/service_07_quantity_surveying.jpg",
    heroImage: "/images/walton/service_07_quantity_surveying.jpg",
    images: [
      "/images/walton/service_07_quantity_surveying.jpg",
      "/images/walton/service_03_construction_mgmt.jpg",
      "/images/walton/service_01_consultancy.jpg",
    ],
    overview:
      "Our certified quantity surveyors provide rigorous cost control across the project lifecycle. From pre-tender Bills of Quantities (BOQs) and rate analyses to interim valuations and variation audits, we eliminate budget creep and financial uncertainty.",
    metrics: [
      { label: "Budgets Controlled", value: "$600M+" },
      { label: "Average Cost Savings", value: "8–14%" },
      { label: "Measurement Standard", value: "CESMM4 / NRM2" },
      { label: "Audit Accuracy", value: "99.8%" },
    ],
    deliverables: [
      "Precision itemized Bills of Quantities (BOQ) with comprehensive technical preambles",
      "Current market rate analysis factoring raw materials, labor productivity, and plant hire",
      "5D BIM automated model-based quantity take-offs eliminating manual measurement errors",
      "Interim payment certificate (IPC) verification, site measurements, and progress billing",
      "Contractual variation claim evaluation and value engineering recommendations",
      "Final account reconciliation, retention release auditing, and asset capitalization reports",
    ],
    technicalSpecs: [
      { key: "Measurement Codes", value: "CESMM4 (Civil Engineering), NRM2 (Building Works), POM(I)" },
      { key: "Cost Software", value: "CostX 5D BIM, CATO, Microsoft Excel Advanced VBA" },
      { key: "Rate Database", value: "Real-time Pakistani commodity & labor index updated quarterly" },
      { key: "Verification", value: "Triple-check reconciliation protocol with on-site physical audits" },
    ],
    pillars: [
      { title: "5D BIM Model Measurement", desc: "Automated quantity extraction directly from 3D Revit models eliminating manual discrepancies.", icon: Calculator },
      { title: "Market Rate Precision", desc: "Quarterly updated databases tracking live steel, cement, fuel, and labor indices.", icon: Award },
      { title: "Interim Valuation Auditing", desc: "Rigorous field physical measurements before certifying subcontractor payment certificates.", icon: CheckCircle2 },
      { title: "Variation Governance", desc: "Contractual substantiation and cost mitigation on all design changes and site variations.", icon: Scale },
    ],
    workflow: [
      { step: "01", title: "Measurement & Take-Offs", desc: "Extracting quantities from structural and architectural drawings using CESMM4 rules." },
      { step: "02", title: "Rate Formulation & BOQ", desc: "Conducting composite rate analyses and publishing priced tender Bills of Quantities." },
      { step: "03", title: "Post-Contract Valuations", desc: "Monthly physical site audits, interim payment certification, and cash-flow reporting." },
      { step: "04", title: "Final Account Closeout", desc: "Audit of final quantities, variation adjustments, and retention fund clearances." },
    ],
    faqs: [
      { q: "What measurement rules do you use for civil engineering works?", a: "We follow CESMM4 (Civil Engineering Standard Method of Measurement) and NRM2 for vertical buildings." },
      { q: "Can Walton assist with contractor variation disputes?", a: "Yes, our certified quantity surveyors evaluate contractual basis, rate justifications, and delay claims." },
      { q: "Do you provide model-based 5D BIM take-offs?", a: "Yes, we link 3D geometry to live cost databases for real-time budget forecasting as designs evolve." },
    ],
  },
  {
    id: "contract-management",
    slug: "procurement-contract-management",
    title: "Procurement & Contract Management",
    subtitle: "Tendering, FIDIC Contracts, Vendor Sourcing & Dispute Avoidance",
    eyebrow: "Commercial Contracts & Procurement",
    category: "Contracts & Procurement",
    tag: "Contract Management",
    icon: FileSpreadsheet,
    image: "/images/walton/service_08_contract_mgmt.jpg",
    heroImage: "/images/walton/service_08_contract_mgmt.jpg",
    images: [
      "/images/walton/service_08_contract_mgmt.jpg",
      "/images/walton/about_conference_plans.jpg",
      "/images/walton/service_02_project_mgmt.jpg",
    ],
    overview:
      "Walton oversees complex procurement and contract administration. We draft robust tender documents, structure FIDIC-compliant contracts, evaluate technical bids, manage international supply chains, and administer claims to ensure seamless commercial governance.",
    metrics: [
      { label: "Contracts Administered", value: "320+" },
      { label: "Claims Resolved", value: "99% Out-of-Court" },
      { label: "Contract Frameworks", value: "FIDIC / PEC Standard" },
      { label: "Procurement Network", value: "25+ Countries" },
    ],
    deliverables: [
      "Drafting transparent tender dossiers, conditions of contract, and employer requirements",
      "Technical and commercial contractor bid evaluation and tender negotiation reports",
      "Contract drafting utilizing FIDIC Red, Yellow, Silver, and EPC turnkey formats",
      "International procurement management for specialized mechanical and structural imports",
      "Contractual claim assessment, extension of time (EOT) analysis, and variation orders",
      "Dispute avoidance protocols, mediation documentation, and final closeout settlement",
    ],
    technicalSpecs: [
      { key: "Contract Standards", value: "FIDIC suite (1999 & 2017 Editions), PEC Standard Bidding Documents" },
      { key: "Procurement Rules", value: "Public Procurement Regulatory Authority (PPRA) compliance" },
      { key: "Legal Framework", value: "Arbitration Act, English Common Law, and Pakistani Contract Law" },
      { key: "Supply Chain", value: "Direct mills sourcing for rebar, structural steel, and specialized plant" },
    ],
    pillars: [
      { title: "FIDIC Contract Expertise", desc: "Deep familiarity with FIDIC Red, Yellow, and EPC Silver books protecting employer interests.", icon: FileSpreadsheet },
      { title: "Global Supply Chain Sourcing", desc: "Direct mill relationships for ASTM steel rebar, MEP plant, and specialized machinery.", icon: Truck },
      { title: "EOT & Claim Mitigation", desc: "Rigorous time-impact delay analysis resolving Extension of Time claims equitably.", icon: Scale },
      { title: "Dispute Avoidance", desc: "Proactive contract administration averting formal arbitration and preserving partnerships.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Tender Dossier Formulation", desc: "Preparing conditions of contract, technical specifications, and evaluation criteria." },
      { step: "02", title: "Contractor Prequalification & Bidding", desc: "Issuing tenders, conducting pre-bid conferences, and evaluating commercial proposals." },
      { step: "03", title: "Contract Administration & Claims", desc: "Managing variation requests, payment approvals, and contractual correspondence." },
      { step: "04", title: "Commercial Closeout & Warranties", desc: "Executing final account settlements, performance bond releases, and defect warranties." },
    ],
    faqs: [
      { q: "What contract forms do you specialize in?", a: "We specialize in FIDIC (Red, Yellow, and Silver Books), PEC Standard Bidding Documents, and turnkey EPC contracts." },
      { q: "How do you evaluate contractor delay claims?", a: "We perform time-impact critical path delay analysis to objectively determine contractor vs. employer responsibility." },
      { q: "Can Walton handle international import procurement?", a: "Yes, we manage international letters of credit (LC), customs clearances, and bonded freight logistics." },
    ],
  },
];

export function getWaltonServiceBySlug(slug) {
  if (!slug) return null;
  return (
    WALTON_SERVICES.find(
      (s) =>
        s.slug === slug ||
        s.id === slug ||
        s.slug.replace(/-/g, "") === slug.replace(/-/g, "")
    ) || null
  );
}
