// Solutions Dataset for Walton Consultants & Contracting
import {
  Layers,
  Building2,
  Trees,
  Compass,
  Hammer,
  Leaf,
  Truck,
  Factory,
  CheckCircle2,
  ShieldCheck,
  Award,
  Calculator,
  Zap,
} from "lucide-react";

export const WALTON_SOLUTIONS = [
  {
    id: "infrastructure-solutions",
    slug: "infrastructure-solutions",
    name: "Infrastructure Solutions",
    title: "Infrastructure Solutions",
    subtitle: "Turnkey Transportation Corridors, Bridges & Interchanges",
    eyebrow: "Civil & Transportation Infrastructure",
    tag: "Highways & Expressways",
    icon: Layers,
    image: "/images/walton/solution_01_infrastructure.jpg",
    heroImage: "/images/walton/solution_01_infrastructure.jpg",
    desc: "Complete civil infrastructure delivery covering arterial expressways, prestressed river bridges, grade-separated flyovers, and storm drainage networks built to heavy axle load specifications.",
    overview: "Complete civil infrastructure delivery covering arterial expressways, prestressed river bridges, grade-separated flyovers, and storm drainage networks built to heavy axle load specifications.",
    stats: [
      { label: "Corridor Network", value: "650+ km" },
      { label: "Bridge Superstructures", value: "48 Units" },
      { label: "Design Life Span", value: "100 Years" },
    ],
    metrics: [
      { label: "Corridor Network", value: "650+ km" },
      { label: "Bridge Superstructures", value: "48 Units" },
      { label: "Design Life Span", value: "100 Years" },
    ],
    highlights: [
      "Heavy axle load design compliance (AASHTO / NHA)",
      "High-speed laser paving with polymer-modified asphalt",
      "Segmental prestressed concrete box girders",
      "Integrated regional stormwater conveyance networks",
    ],
    deliverables: [
      "Heavy axle load design compliance (AASHTO / NHA)",
      "High-speed laser paving with polymer-modified asphalt",
      "Segmental prestressed concrete box girders",
      "Integrated regional stormwater conveyance networks",
    ],
    technicalSpecs: [
      { key: "Highway Design", value: "AASHTO A Policy on Geometric Design of Highways and Streets" },
      { key: "Bridge Code", value: "AASHTO LRFD Bridge Design Specifications" },
      { key: "Asphalt Grade", value: "Superpave Polymer-Modified Bitumen (PMB)" },
    ],
    pillars: [
      { title: "Long-Span Bridge Engineering", desc: "Prestressed concrete box girders designed for high-volume freight transit.", icon: Layers },
      { title: "Laser Paving Precision", desc: "Automated screeds ensuring superior International Roughness Index.", icon: Compass },
      { title: "Regional Storm Drainage", desc: "High-capacity concrete box culverts mitigating monsoon flood hazards.", icon: Award },
      { title: "Intelligent Traffic Control", desc: "Fiber-optic linked dynamic signage, CCTV surveillance, and tolling.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Topographic & Geotechnical Surveys", desc: "Digital elevation models and deep borehole core profiling." },
      { step: "02", title: "Sub-Base & Culvert Construction", desc: "Granular fill compaction and reinforced concrete culvert installation." },
      { step: "03", title: "Bridge Pier & Girder Erection", desc: "Rotary piling, pier caps, and post-tensioned beam launching." },
      { step: "04", title: "Asphalt Paving & Commissioning", desc: "Wearing course paving, thermal markings, and safety barriers." },
    ],
    faqs: [
      { q: "What design life is built into Walton's infrastructure solutions?", a: "Our major highway structures and bridges are engineered for a 100-year design life under AASHTO standards." },
      { q: "Can Walton handle challenging river crossings?", a: "Yes, we have built over 48 river bridges and elevated viaducts using deep bored piling up to 48 meters deep." },
    ],
  },
  {
    id: "construction-solutions",
    slug: "construction-solutions",
    name: "Construction Solutions",
    title: "Construction Solutions",
    subtitle: "Heavy Civil Contracting, Superstructures & Foundations",
    eyebrow: "Commercial & Institutional Contracting",
    tag: "Civil & Superstructures",
    icon: Hammer,
    image: "/images/walton/solution_02_construction.jpg",
    heroImage: "/images/walton/solution_02_construction.jpg",
    desc: "End-to-end commercial and institutional building construction with high-strength concrete framing, post-tensioned slabs, deep secant pile basements, and architectural building envelopes.",
    overview: "End-to-end commercial and institutional building construction with high-strength concrete framing, post-tensioned slabs, deep secant pile basements, and architectural building envelopes.",
    stats: [
      { label: "Built Floor Space", value: "8.5M+ sq ft" },
      { label: "Deep Foundation Piling", value: "45m Depth" },
      { label: "Concrete Grade", value: "C50/60 High-Strength" },
    ],
    metrics: [
      { label: "Built Floor Space", value: "8.5M+ sq ft" },
      { label: "Deep Foundation Piling", value: "45m Depth" },
      { label: "Concrete Grade", value: "C50/60 High-Strength" },
    ],
    highlights: [
      "Hydraulic self-climbing core formwork systems",
      "Post-tensioned beam-free clear spans up to 12 meters",
      "Full seismic ductility detailing for UBC Zone 3 & 4",
      "Unitized architectural curtain wall glazing facades",
    ],
    deliverables: [
      "Hydraulic self-climbing core formwork systems",
      "Post-tensioned beam-free clear spans up to 12 meters",
      "Full seismic ductility detailing for UBC Zone 3 & 4",
      "Unitized architectural curtain wall glazing facades",
    ],
    technicalSpecs: [
      { key: "Building Codes", value: "Building Code of Pakistan (BCP), ACI 318-19, ASCE 7-16" },
      { key: "Formwork Technology", value: "Doka hydraulic climbing cores, Peri modular decking" },
      { key: "Foundation Support", value: "Secant pile shoring with pre-stressed ground tiebacks" },
    ],
    pillars: [
      { title: "Seismic Ductile Cores", desc: "Dual shear wall structural cores engineered to absorb dynamic seismic energy.", icon: ShieldCheck },
      { title: "Post-Tensioned Slabs", desc: "Thin, long-span slabs eliminating interior beams for maximum interior volume.", icon: Building2 },
      { title: "Deep Substructure Shoring", desc: "Contiguous retaining walls allowing safe excavation up to 4 basement levels.", icon: Hammer },
      { title: "Architectural Envelope", desc: "High-performance double-glazed unitized curtain wall installations.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Piling & Basement Excavation", desc: "Installing perimeter retaining piles and deep subterranean earth removal." },
      { step: "02", title: "Raft Foundation & Substructure", desc: "Mass concrete raft casting with ice-chilled batching plants." },
      { step: "03", title: "Superstructure Frame Erection", desc: "Climbing core formwork and post-tensioned floor casting." },
      { step: "04", title: "Enclosure & Handover", desc: "Unitized facade installation, MEP commissioning, and occupancy clearance." },
    ],
    faqs: [
      { q: "What height commercial towers can Walton construct?", a: "We have built towers up to 45 storeys with 4-level deep basements." },
      { q: "How do you control concrete cracking in thick foundations?", a: "We use ice-chilled water batching, low-heat pozzolanic cement, and digital thermal sensors." },
    ],
  },
  {
    id: "urban-development",
    slug: "urban-development",
    name: "Urban Development",
    title: "Urban Development",
    subtitle: "Smart City Master Planning, Mixed-Use & Civic Plazas",
    eyebrow: "Urban Master Planning & Mixed-Use",
    tag: "Urban & Master Planning",
    icon: Building2,
    image: "/images/walton/solution_03_urban.jpg",
    heroImage: "/images/walton/solution_03_urban.jpg",
    desc: "Transformative urban developments that blend high-density commercial skyscrapers, public open green spaces, multi-modal transit connectivity, and smart municipal utilities.",
    overview: "Transformative urban developments that blend high-density commercial skyscrapers, public open green spaces, multi-modal transit connectivity, and smart municipal utilities.",
    stats: [
      { label: "Master Planned Area", value: "12,000+ Acres" },
      { label: "Commercial Districts", value: "15+" },
      { label: "Green Space Ratio", value: "35% Minimum" },
    ],
    metrics: [
      { label: "Master Planned Area", value: "12,000+ Acres" },
      { label: "Commercial Districts", value: "15+" },
      { label: "Green Space Ratio", value: "35% Minimum" },
    ],
    highlights: [
      "Integrated pedestrian boulevards and multi-modal mobility",
      "Underground municipal utility tunnels and storm management",
      "Bioclimatic spatial microclimate optimization",
      "High-efficiency leasable floor plate yield maximization",
    ],
    deliverables: [
      "Integrated pedestrian boulevards and multi-modal mobility",
      "Underground municipal utility tunnels and storm management",
      "Bioclimatic spatial microclimate optimization",
      "High-efficiency leasable floor plate yield maximization",
    ],
    technicalSpecs: [
      { key: "Master Planning Standards", value: "Urban Land Institute (ULI) Guidelines, Local Master Plans" },
      { key: "Green Space Ratio", value: "35% minimum dedicated parks, water retention, and boulevards" },
      { key: "Mobility Integration", value: "Transit-Oriented Development (TOD) with dedicated bus loops" },
    ],
    pillars: [
      { title: "Transit-Oriented Design", desc: "Seamless integration between public transit nodes and commercial hubs.", icon: Building2 },
      { title: "Underground Utilities", desc: "Walkable utility corridors housing power, water, fiber, and stormwater.", icon: Compass },
      { title: "Bioclimatic Plazas", desc: "Civic open areas designed to optimize shade and natural breeze corridors.", icon: Leaf },
      { title: "Smart City Infrastructure", desc: "Central IoT monitoring for streetlights, water pressure, and waste.", icon: Zap },
    ],
    workflow: [
      { step: "01", title: "Regional Spatial Analysis", desc: "Evaluating traffic flows, growth vectors, and environmental topography." },
      { step: "02", title: "Master Plan & Zoning Design", desc: "Formulating land use zoning, road hierarchies, and utility layouts." },
      { step: "03", title: "Trunk Utility Infrastructure", desc: "Excavating and casting underground electrical and water conduits." },
      { step: "04", title: "Commercial Development & Handover", desc: "Executing commercial towers and public landscaped civic centers." },
    ],
    faqs: [
      { q: "What is the typical scale of Walton's urban master plans?", a: "We have master planned developments ranging from 50-acre corporate tech parks up to 12,000-acre regional townships." },
      { q: "Does Walton coordinate municipal approvals?", a: "Yes, we handle zoning submissions and master plan sanctioning with development authorities." },
    ],
  },
  {
    id: "project-advisory",
    slug: "project-advisory",
    name: "Project Advisory",
    title: "Project Advisory",
    subtitle: "Feasibility Studies, Risk Analysis & Technical Peer Reviews",
    eyebrow: "Strategic Feasibility & Risk Advisory",
    tag: "Advisory & Feasibility",
    icon: Compass,
    image: "/images/walton/solution_04_advisory.jpg",
    heroImage: "/images/walton/solution_04_advisory.jpg",
    desc: "Strategic technical, financial, and regulatory consulting for mega projects. We derisk major capital investments through rigorous engineering feasibility and bankable reports.",
    overview: "Strategic technical, financial, and regulatory consulting for mega projects. We derisk major capital investments through rigorous engineering feasibility and bankable reports.",
    stats: [
      { label: "Studies Delivered", value: "280+" },
      { label: "Bankable Accuracy", value: "±3.5%" },
      { label: "Financed Value", value: "$1.2B+" },
    ],
    metrics: [
      { label: "Studies Delivered", value: "280+" },
      { label: "Bankable Accuracy", value: "±3.5%" },
      { label: "Financed Value", value: "$1.2B+" },
    ],
    highlights: [
      "LiDAR aerial surveying and geotechnical profiling",
      "Traffic volume simulation and lifecycle cost modeling",
      "Environmental & Social Impact Assessments (ESIA)",
      "Bankable financial modeling for institutional investors",
    ],
    deliverables: [
      "LiDAR aerial surveying and geotechnical profiling",
      "Traffic volume simulation and lifecycle cost modeling",
      "Environmental & Social Impact Assessments (ESIA)",
      "Bankable financial modeling for institutional investors",
    ],
    technicalSpecs: [
      { key: "Financial Modeling", value: "Discounted cash flow (DCF), Monte Carlo risk simulations, IRR" },
      { key: "Survey Precision", value: "Sub-centimeter RTK GPS and drone LiDAR terrain mapping" },
      { key: "Environmental Framework", value: "World Bank Environmental & Social Standards (ESS)" },
    ],
    pillars: [
      { title: "Bankable Financial Models", desc: "Accurate cash-flow and debt-service forecasts validated by institutional lenders.", icon: Calculator },
      { title: "Geological Risk Elimination", desc: "Exhaustive soil borehole drilling uncovering subterranean foundation hazards.", icon: Compass },
      { title: "Traffic Revenue Forecasts", desc: "Origin-destination traffic modeling predicting expressway toll revenues.", icon: Truck },
      { title: "Regulatory Due Diligence", desc: "Environmental clearance dossiers securing fast-track EPA sanctioning.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Preliminary Opportunity Review", desc: "Scoping site constraints, legal entitlements, and market demand." },
      { step: "02", title: "Field Surveys & Testing", desc: "Conducting drone topographic mapping and borehole soil testing." },
      { step: "03", title: "Engineering Cost & Revenue Model", desc: "Calculating CAPEX, OPEX, and lifecycle revenue projections." },
      { step: "04", title: "Bankable Feasibility Dossier", desc: "Publishing comprehensive institutional report for financing." },
    ],
    faqs: [
      { q: "Are your feasibility studies accepted by international banks?", a: "Yes, our reports meet World Bank, ADB, and international commercial banking criteria." },
      { q: "Do you offer technical due diligence for acquisitions?", a: "Yes, we audit physical structures, MEP plants, and regulatory compliance for investors." },
    ],
  },
  {
    id: "engineering-solutions",
    slug: "engineering-solutions",
    name: "Engineering Solutions",
    title: "Engineering Solutions",
    subtitle: "Structural Engineering, 3D BIM Clash Detection & Geotech",
    eyebrow: "Structural & Geotechnical Engineering",
    tag: "Structural & Geotechnical",
    icon: ShieldCheck,
    image: "/images/walton/solution_05_engineering.jpg",
    heroImage: "/images/walton/solution_05_engineering.jpg",
    desc: "Cutting-edge structural and geotechnical engineering solutions utilizing finite-element modeling, Building Information Modeling (BIM Level 2/3), and advanced soil mechanics.",
    overview: "Cutting-edge structural and geotechnical engineering solutions utilizing finite-element modeling, Building Information Modeling (BIM Level 2/3), and advanced soil mechanics.",
    stats: [
      { label: "Engineering Designs", value: "450+" },
      { label: "Design Codes", value: "ACI 318 / ASCE 7" },
      { label: "BIM Clash Reduction", value: "98% Pre-Pour" },
    ],
    metrics: [
      { label: "Engineering Designs", value: "450+" },
      { label: "Design Codes", value: "ACI 318 / ASCE 7" },
      { label: "BIM Clash Reduction", value: "98% Pre-Pour" },
    ],
    highlights: [
      "Non-linear dynamic earthquake response simulations",
      "Complex deep excavation shoring and tieback systems",
      "Full 3D BIM multi-discipline clash detection in Revit",
      "Structural peer review and value engineering audits",
    ],
    deliverables: [
      "Non-linear dynamic earthquake response simulations",
      "Complex deep excavation shoring and tieback systems",
      "Full 3D BIM multi-discipline clash detection in Revit",
      "Structural peer review and value engineering audits",
    ],
    technicalSpecs: [
      { key: "Analysis Suites", value: "ETABS Ultimate, CSI Bridge, SAFE, SAP2000, Plaxis 2D/3D" },
      { key: "BIM Maturity", value: "Level 2 / 3 (ISO 19650 compliant digital workflows)" },
      { key: "Design Codes", value: "ACI 318-19, AISC 360-16, ASCE 7-16, UBC-97" },
    ],
    pillars: [
      { title: "Dynamic Earthquake Analysis", desc: "Non-linear time-history response spectra simulations safeguarding structures.", icon: ShieldCheck },
      { title: "Deep Shoring Engineering", desc: "Diaphragm walls and ground anchor design protecting adjacent properties.", icon: Hammer },
      { title: "BIM Constructability Reviews", desc: "Automated clash resolution preventing costly field re-work before pouring.", icon: Layers },
      { title: "Value Engineering", desc: "Rebar and concrete volume optimization preserving structural integrity.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Geotechnical Data Integration", desc: "Digitizing borehole logs and soil spring stiffness profiles." },
      { step: "02", title: "3D Finite Element Modeling", desc: "Constructing full structural model subjected to wind and seismic loads." },
      { step: "03", title: "BIM Coordination & Detailing", desc: "Resolving MEP clashes and producing stamped structural drawings." },
      { step: "04", title: "Site Engineering Oversight", desc: "Reviewing rebar cages, formwork, and non-destructive test results." },
    ],
    faqs: [
      { q: "What software does Walton use for structural analysis?", a: "We utilize ETABS Ultimate, SAFE, CSI Bridge, and SAP2000 for structural modeling." },
      { q: "Can you provide independent structural vetting?", a: "Yes, our certified structural engineers perform formal third-party peer reviews." },
    ],
  },
  {
    id: "sustainable-infrastructure",
    slug: "sustainable-infrastructure",
    name: "Sustainable Infrastructure",
    title: "Sustainable Infrastructure",
    subtitle: "Renewable Energy Integration, Green Buildings & Water Recycling",
    eyebrow: "Eco-Resilient & Net-Zero Construction",
    tag: "Sustainability & Green EPC",
    icon: Leaf,
    image: "/images/walton/solution_06_sustainable.jpg",
    heroImage: "/images/walton/solution_06_sustainable.jpg",
    desc: "Eco-resilient engineering integrating rooftop solar photovoltaic arrays, rainwater harvesting, permeable pavements, and low-carbon cement formulations for net-zero impact.",
    overview: "Eco-resilient engineering integrating rooftop solar photovoltaic arrays, rainwater harvesting, permeable pavements, and low-carbon cement formulations for net-zero impact.",
    stats: [
      { label: "Renewable Capacity", value: "85 MW" },
      { label: "Carbon Reduction", value: "35% Average" },
      { label: "Water Recycled", value: "1.8M Gallons/day" },
    ],
    metrics: [
      { label: "Renewable Capacity", value: "85 MW" },
      { label: "Carbon Reduction", value: "35% Average" },
      { label: "Water Recycled", value: "1.8M Gallons/day" },
    ],
    highlights: [
      "LEED Gold and Platinum engineering compliance",
      "Commercial solar canopy and microgrid integration",
      "Greywater biological recycling and retention basins",
      "Recycled aggregate concrete and slag mix optimization",
    ],
    deliverables: [
      "LEED Gold and Platinum engineering compliance",
      "Commercial solar canopy and microgrid integration",
      "Greywater biological recycling and retention basins",
      "Recycled aggregate concrete and slag mix optimization",
    ],
    technicalSpecs: [
      { key: "Green Standards", value: "USGBC LEED v4.1, EDGE Green Building, ASHRAE 90.1" },
      { key: "Renewable Scope", value: "Rooftop PV, solar carport canopies, battery energy storage (BESS)" },
      { key: "Water Efficiency", value: "Greywater treatment, permeable pavers, native xeriscaping" },
    ],
    pillars: [
      { title: "Commercial Solar Power", desc: "Turnkey rooftop and ground-mount PV generating clean renewable electricity.", icon: Zap },
      { title: "Low-Carbon Concrete", desc: "Mix designs incorporating industrial slag (GGBS) reducing embodied carbon.", icon: Leaf },
      { title: "Closed-Loop Water Recycling", desc: "Effluent treatment plants converting wastewater into irrigation water.", icon: Compass },
      { title: "LEED Gold Delivery", desc: "End-to-end certification documentation securing international green badges.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Energy & Carbon Audit", desc: "Benchmarking baseline energy, water, and material carbon intensity." },
      { step: "02", title: "Sustainable System Design", desc: "Integrating solar PV, rainwater retention, and energy-efficient building envelopes." },
      { step: "03", title: "Green Construction Execution", desc: "Managing waste recycling, low-VOC materials, and low-carbon concrete." },
      { step: "04", title: "Commissioning & Certification", desc: "Conducting thermal envelope commissioning and LEED certification filing." },
    ],
    faqs: [
      { q: "How much energy can rooftop solar save on an industrial facility?", a: "Depending on roof area, rooftop solar typically offsets 30% to 65% of daytime utility energy costs." },
      { q: "Does Walton design industrial wastewater treatment plants?", a: "Yes, we construct biological effluent treatment plants (ETP) meeting all environmental standards." },
    ],
  },
  {
    id: "transportation-solutions",
    slug: "transportation-solutions",
    name: "Transportation Solutions",
    title: "Transportation Solutions",
    subtitle: "Multi-Modal Freight Corridors, Mass Transit & Intelligent Roads",
    eyebrow: "Mobility & Regional Corridors",
    tag: "Mobility & Transit",
    icon: Truck,
    image: "/images/walton/solution_07_transport.jpg",
    heroImage: "/images/walton/solution_07_transport.jpg",
    desc: "Modern transport engineering connecting metropolitan nodes through dedicated bus rapid transit (BRT) routes, railway bridges, heavy freight corridors, and smart tolling plazas.",
    overview: "Modern transport engineering connecting metropolitan nodes through dedicated bus rapid transit (BRT) routes, railway bridges, heavy freight corridors, and smart tolling plazas.",
    stats: [
      { label: "Dedicated Transit", value: "120+ km" },
      { label: "Freight Capacity", value: "100K Vehicles/day" },
      { label: "Safety Index", value: "AASHTO 5-Star" },
    ],
    metrics: [
      { label: "Dedicated Transit", value: "120+ km" },
      { label: "Freight Capacity", value: "100K Vehicles/day" },
      { label: "Safety Index", value: "AASHTO 5-Star" },
    ],
    highlights: [
      "Grade-separated BRT flyovers and passenger terminals",
      "Automated electronic toll collection (ETC) gantries",
      "Heavy freight corridor axle load enforcement weigh stations",
      "Dynamic LED traffic guidance and fiber network backbones",
    ],
    deliverables: [
      "Grade-separated BRT flyovers and passenger terminals",
      "Automated electronic toll collection (ETC) gantries",
      "Heavy freight corridor axle load enforcement weigh stations",
      "Dynamic LED traffic guidance and fiber network backbones",
    ],
    technicalSpecs: [
      { key: "Highway Standards", value: "AASHTO Geometric Design, NHA Highway Safety Manual" },
      { key: "Transit Structures", value: "Grade-separated precast viaducts and steel truss pedestrian bridges" },
      { key: "Intelligent Systems", value: "RFID electronic toll collection (ETC) and weigh-in-motion (WIM)" },
    ],
    pillars: [
      { title: "High-Capacity Corridors", desc: "Pavements engineered for continuous heavy truck traffic without rutting.", icon: Truck },
      { title: "Rapid Transit Viaducts", desc: "Elevated transit busways bypassing congested metropolitan street networks.", icon: Layers },
      { title: "Automated Tolling Gantries", desc: "High-speed RFID electronic toll collection eliminating toll plaza delays.", icon: Zap },
      { title: "Highway Safety Engineering", desc: "W-beam guardrails, impact attenuators, and high-visibility road markings.", icon: ShieldCheck },
    ],
    workflow: [
      { step: "01", title: "Traffic Volume & Demand Modeling", desc: "Origin-destination modeling predicting vehicle growth over 25 years." },
      { step: "02", title: "Geometric & Structural Design", desc: "Optimizing vertical curves, super-elevation, and bridge spans." },
      { step: "03", title: "Corridor Construction", desc: "Laser-guided grading, sub-base compaction, and asphalt paving." },
      { step: "04", title: "ITS & Tolling Deployment", desc: "Installing fiber communications, CCTV loops, and electronic toll gates." },
    ],
    faqs: [
      { q: "What traffic volumes can your highway corridors accommodate?", a: "Our corridors are designed for over 100,000 passenger car units (PCU) per day." },
      { q: "Do you install electronic toll collection (ETC) systems?", a: "Yes, we deliver turnkey tolling plazas with RFID sensors, automated boom gates, and cash management." },
    ],
  },
  {
    id: "industrial-development",
    slug: "industrial-development",
    name: "Industrial Development",
    title: "Industrial Development",
    subtitle: "Turnkey Industrial Plants, PEB Steel Warehouses & Utilities",
    eyebrow: "Industrial EPC & Pre-Engineered Buildings",
    tag: "Industrial EPC",
    icon: Factory,
    image: "/images/walton/solution_08_industrial.jpg",
    heroImage: "/images/walton/solution_08_industrial.jpg",
    desc: "Full EPC industrial solutions for manufacturing complexes, logistics centers, pre-engineered structural steel buildings (PEB), high-voltage substations, and heavy machinery pits.",
    overview: "Full EPC industrial solutions for manufacturing complexes, logistics centers, pre-engineered structural steel buildings (PEB), high-voltage substations, and heavy machinery pits.",
    stats: [
      { label: "Industrial Complexes", value: "85 Plants" },
      { label: "Covered Steel Area", value: "8.5M+ sq ft" },
      { label: "Substations Built", value: "Up to 132kV" },
    ],
    metrics: [
      { label: "Industrial Complexes", value: "85 Plants" },
      { label: "Covered Steel Area", value: "8.5M+ sq ft" },
      { label: "Substations Built", value: "Up to 132kV" },
    ],
    highlights: [
      "Heavy machine dynamic vibration isolation foundation slabs",
      "Pre-engineered building (PEB) high-yield structural frames",
      "High-voltage electrical switchgear, substations, and MCCs",
      "Industrial fire suppression and effluent treatment plants",
    ],
    deliverables: [
      "Heavy machine dynamic vibration isolation foundation slabs",
      "Pre-engineered building (PEB) high-yield structural frames",
      "High-voltage electrical switchgear, substations, and MCCs",
      "Industrial fire suppression and effluent treatment plants",
    ],
    technicalSpecs: [
      { key: "Contract Model", value: "Turnkey Lump-Sum EPC / FIDIC Silver Book" },
      { key: "Structural Steel", value: "High-yield ASTM A572 Grade-50 steel portal frames up to 45m span" },
      { key: "Electrical Substation", value: "11kV to 132kV grid connection substations with vacuum breakers" },
    ],
    pillars: [
      { title: "Dynamic Machine Beds", desc: "Finite element vibration-damped foundation pads for heavy presses.", icon: Factory },
      { title: "Wide Clear-Span PEBs", desc: "Column-free structural steel frames maximizing warehouse floor storage.", icon: Building2 },
      { title: "Substation Engineering", desc: "Industrial high-voltage power distribution and motor control centers.", icon: Zap },
      { title: "Turnkey Handover", desc: "Single-point delivery from foundation to trial production run.", icon: Award },
    ],
    workflow: [
      { step: "01", title: "Process Layout & FEED", desc: "Collaborating with equipment suppliers to design foundation pits and loads." },
      { step: "02", title: "Civil Foundations & Slab Casting", desc: "Casting laser-flat floor slabs and dynamic machine vibration beds." },
      { step: "03", title: "Structural Steel Erection", desc: "Rigging and assembling heavy portal frames and standing seam roofs." },
      { step: "04", title: "Utilities & Commissioning", desc: "Installing substations, piping loops, fire rings, and testing runs." },
    ],
    faqs: [
      { q: "What industries has Walton built factories for?", a: "We have built plants for textiles, FMCG, automotive assembly, chemical processing, and cold-storage logistics." },
      { q: "Does Walton provide single-point EPC contracts?", a: "Yes, our turnkey EPC covers civil, structural steel, electrical substations, piping, and commissioning." },
    ],
  },
];

export function getWaltonSolutionBySlug(slug) {
  if (!slug) return null;
  return (
    WALTON_SOLUTIONS.find(
      (s) =>
        s.slug === slug ||
        s.id === slug ||
        s.slug.replace(/-/g, "") === slug.replace(/-/g, "")
    ) || null
  );
}
