export const COMPANY_INFO = {
  name: "Max Pak Corporation",
  shortName: "Max Pak",
  tagline: "Industrial Trading & Commercial Supplies",
  group: "A Flagship Enterprise of Roy Sons Pvt. Ltd.",
  established: 1994,
  hq: "Roy Sons Corporate Complex, Sector G-5, Islamabad, Pakistan",
  warehouses: "Lahore Central Logistics Hub & Karachi Port Bonded Yard",
  phone: "0092-42-38924737 / 0092-321-8431665",
  whatsapp: "0092-304-7527498",
  email: "info@roysons.org",
  salesEmail: "sales@maxpak.roysons.org",
  stats: {
    yearsOfExcellence: "30+",
    productsSupplied: "10,000+",
    projectsCompleted: "2,500+",
    corporateClients: "800+",
    onTimeDelivery: "99.2%",
    inventoryStock: "$45M+",
  },
};

export const HERO_SLIDES = [
  {
    id: 1,
    title: "Heavy Industrial Machinery & Robotic Manufacturing Lines",
    subtitle: "Turnkey CNC Milling · Industrial Robotic Automation · German Engineering",
    description:
      "Direct authorized distribution of multi-axis CNC machine centers, heavy fabrication systems, and automated robotic assembly plants engineered to deliver micro-precision productivity.",
    image: "/maxpak/hero_heavy_industry.jpg",
    badge: "Industrial Machinery",
    statLabel: "Installed Machinery",
    statValue: "1,850+ Units",
    accent: "#16A34A",
  },
  {
    id: 2,
    title: "ASTM Certified Structural Steel & High-Tensile Rebar",
    subtitle: "Grade 60 Deformed Rebar · Wide-Flange H-Beams · Certified MTC Traceability",
    description:
      "High-volume inventory and scheduled site delivery of ASTM A615 Grade 60 rebar, European wide-flange beams, and structural channels backed by EN 10204 3.1 Mill Test Certificates.",
    image: "/maxpak/structural_steel_rebar.jpg",
    badge: "Structural Steel",
    statLabel: "Steel Supplied",
    statValue: "250,000+ MT",
    accent: "#0072CE",
  },
  {
    id: 3,
    title: "Heavy Crawler Excavators & 500-Ton Mobile Lifting Cranes",
    subtitle: "CAT / Komatsu Earthmoving Fleet · All-Terrain Heavy Cranes · Job-Ready Logistics",
    description:
      "Comprehensive machinery supply from 20-to-85-ton hydraulic crawler excavators to 500-ton all-terrain cranes, complete with on-site commissioning and genuine OEM spare parts support.",
    image: "/maxpak/earthmoving_excavators.jpg",
    badge: "Earthmoving & Lifting",
    statLabel: "Fleet Readiness",
    statValue: "100% Certified",
    accent: "#EAB308",
  },
  {
    id: 4,
    title: "High-Pressure API Pipeline Valves & Cryogenic Flanges",
    subtitle: "API 6D Pipeline Ball Valves · ASME Class 1500 Flanges · NACE MR0175",
    description:
      "Sourcing extreme-duty ball, gate, and check valves, pneumatic actuators, and forged steel pipe fittings for upstream oilfields, chemical refineries, and high-pressure steam utility plants.",
    image: "/maxpak/industrial_valves_piping.jpg",
    badge: "Valves & Piping",
    statLabel: "Pressure Rating",
    statValue: "Up to 6,000 PSI",
    accent: "#EF4444",
  },
  {
    id: 5,
    title: "Medium & High-Voltage Electrical Substation Switchgear",
    subtitle: "11kV / 132kV Vacuum Switchgear · 25 MVA Power Transformers · IEC 62271",
    description:
      "Supplying utility-grade medium and high-voltage vacuum circuit breakers, motor control centers (MCC), and industrial power transformers engineered for continuous round-the-clock uptime.",
    image: "/maxpak/electrical_switchgear.jpg",
    badge: "Electrical Switchgear",
    statLabel: "Grid Capacity",
    statValue: "500+ MW Powered",
    accent: "#10B981",
  },
];

export const INDUSTRIAL_CATEGORIES = [
  "All",
  "Heavy Machinery & CNC Tools",
  "Structural Steel & Construction Rebar",
  "Heavy Earthmoving & Lifting Fleet",
  "Industrial Valves & Pipeline Fittings",
  "Electrical Switchgear & Power Systems",
  "Turnkey EPC Plants & Commercial Supplies",
];

export const FULL_CATALOG_LISTINGS = [
  // ─── 1. HEAVY MACHINERY & CNC TOOLS ───
  {
    id: "mp-mach-01",
    sku: "MP-CNC-5AX",
    title: "5-Axis High-Precision CNC Vertical Machining Center",
    category: "Heavy Machinery & CNC Tools",
    origin: "Germany & Japan (Authorized Distribution)",
    leadTime: "3 - 6 Weeks Delivery / Commissioning",
    compliance: "CE Marked, ISO 9001, DIN 8615 Precision Standard",
    image: "/maxpak/cnc_workshop.jpg",
    description:
      "Ultra-precision 5-axis vertical machining center engineered for aerospace, automotive dies, and heavy machinery parts requiring complex geometric tolerances.",
    features: [
      "High-speed 20,000 RPM direct-drive spindle with ceramic hybrid bearings",
      "Heidenhain 5-axis synchronous continuous CNC controller with 3D simulation",
      "High-pressure 70-bar through-spindle internal coolant filtration system",
      "Pre-installation foundation engineering and on-site factory training included",
    ],
    specs: {
      "Spindle Power": "35 kW High-Torque Continuous Drive",
      "Positioning Accuracy": "±0.003 mm across full XYZ travels",
      "Table Capacity": "1,200 kg maximum workpiece weight",
      "Tool Magazine": "60-Pocket automatic tool changer (ATC)",
      "Warranty": "2-Year Comprehensive OEM Manufacturer Warranty",
    },
    warranty: "2-Year OEM Comprehensive Warranty",
  },
  {
    id: "mp-mach-02",
    sku: "MP-LASER-12K",
    title: "12 kW High-Power Industrial Fiber Laser Cutting Table",
    category: "Heavy Machinery & CNC Tools",
    origin: "Switzerland & South Korea",
    leadTime: "4 - 8 Weeks Ex-Stock / Freight",
    compliance: "CE, FDA Laser Safety Class 4, ISO 14001",
    image: "/maxpak/hero_heavy_industry.jpg",
    description:
      "High-speed 12,000-watt fiber laser cutter capable of processing up to 45mm carbon steel, 30mm stainless steel, and 25mm aluminum with zero dross.",
    features: [
      "Raycus / IPG Photonics solid-state fiber laser resonator source",
      "Dual exchange shuttle loading table reducing cycle downtime to under 15 seconds",
      "Automated optical height-sensing capacitive cutting head with autofocus",
      "Integrated heavy-duty dust extraction and smoke filtration unit",
    ],
    specs: {
      "Cutting Bed Size": "6,000 mm x 2,500 mm dual hydraulic shuttle",
      "Laser Power": "12,000 Watts (12 kW) continuous output",
      "Max Sheet Thickness": "45 mm Carbon Steel / 30 mm Stainless Steel",
      "Max Acceleration": "2.0G dual gantry servo drive acceleration",
      "Cooling Unit": "Dual-circuit precision industrial water chiller",
    },
    warranty: "3-Year Laser Source & Core Electronics Warranty",
  },
  {
    id: "mp-mach-03",
    sku: "MP-PRESS-800",
    title: "800-Ton Hydraulic Metal Stamping & Deep Drawing Press",
    category: "Heavy Machinery & CNC Tools",
    origin: "Italy & Japan",
    leadTime: "6 - 10 Weeks",
    compliance: "OSHA Compliant, CE Machinery Directive 2006/42/EC",
    image: "/maxpak/hero_heavy_industry.jpg",
    description:
      "Heavy four-column hydraulic deep drawing press designed for automotive body panels, gas cylinders, and industrial metal stamping applications.",
    features: [
      "Rigid four-column forged tie-rod structure resisting lateral deflection",
      "Siemens S7 PLC automation with color touchscreen recipe management",
      "Proportional hydraulic valving for micro-controlled pressure ramping",
      "Safety light curtains and dual interlocking mechanical slide locks",
    ],
    specs: {
      "Nominal Force": "8,000 kN (800 Metric Tons)",
      "Bolster Table": "2,200 mm x 1,800 mm T-slot steel bed",
      "Daylight Opening": "1,500 mm vertical daylight height",
      "Pumping System": "Rexroth variable displacement axial piston pumps",
      "Operating Pressure": "250 Bar continuous hydraulic pressure",
    },
    warranty: "2-Year Hydraulic & Structural Warranty",
  },
  {
    id: "mp-mach-04",
    sku: "MP-BORING-130",
    title: "Heavy Floor-Type Horizontal Boring & Milling Machine",
    category: "Heavy Machinery & CNC Tools",
    origin: "Czech Republic & Germany",
    leadTime: "8 - 12 Weeks",
    compliance: "ISO 3070 Boring Machine Standards, CE",
    image: "/maxpak/cnc_workshop.jpg",
    description:
      "Massive floor-type horizontal boring mill designed for machining heavy engine blocks, hydro turbine housings, and large structural fabrications.",
    features: [
      "130mm nitrided high-rigidity chrome-molybdenum boring spindle",
      "Rotary indexing table handling workpieces up to 25 metric tons",
      "Full hydrostatic guideways on X, Y, and Z axes eliminating friction wear",
      "Modular right-angle milling heads and universal universal angular heads",
    ],
    specs: {
      "Spindle Diameter": "130 mm nitrided steel spindle",
      "X-Axis Travel": "8,000 mm horizontal column traverse",
      "Y-Axis Travel": "3,500 mm vertical headstock travel",
      "Table Load": "25,000 kg capacity 360-degree rotary table",
      "Motor Power": "55 kW high-torque spindle motor",
    },
    warranty: "2-Year Mechanical & Controller Guarantee",
  },

  // ─── 2. STRUCTURAL STEEL & CONSTRUCTION REBAR ───
  {
    id: "mp-steel-01",
    sku: "MP-REBAR-G60",
    title: "ASTM A615 Grade 60 High-Yield Deformed Construction Rebar",
    category: "Structural Steel & Construction Rebar",
    origin: "Pakistan Steel Mills & Premier Certified Rolling Mills",
    leadTime: "Immediate Ex-Stock Yard / 48-Hour Site Dispatch",
    compliance: "ASTM A615 / A706 Grade 60, BS 4449 Grade 500B",
    image: "/maxpak/structural_steel_rebar.jpg",
    description:
      "Prime-quality thermo-mechanically treated (TMT) high-tensile deformed reinforcing steel rebar for mega-bridges, high-rise towers, and industrial dams.",
    features: [
      "Certified 60,000 PSI minimum yield strength with superior ductility",
      "Complete EN 10204 3.1 Mill Test Certificates (MTCs) with every consignment",
      "Excellent bendability and weldability resisting seismic micro-cracking",
      "Supplied in straight 12-meter commercial bundles or pre-bent to BBS schedules",
    ],
    specs: {
      "Diameter Range": "10 mm (#3) to 40 mm (#12) standard diameters",
      "Tensile Strength": "90,000 PSI (620 MPa) minimum tensile rating",
      "Yield Strength": "60,000 PSI (420 MPa) minimum yield rating",
      "Elongation": "16% minimum rupture elongation ductility",
      "Chemical Controls": "Carbon equivalent CE < 0.42% for weldability",
    },
    warranty: "100% Chemical & Mechanical Laboratory Certification",
  },
  {
    id: "mp-steel-02",
    sku: "MP-BEAM-HEA",
    title: "Wide-Flange Structural Steel H-Beams & I-Sections",
    category: "Structural Steel & Construction Rebar",
    origin: "European Union, Turkey & South Korea",
    leadTime: "Ex-Stock Warehouse / Direct Mill Shipment",
    compliance: "EN 10025-2 S355JR / S275JR, ASTM A36 / A572 Grade 50",
    image: "/maxpak/structural_steel_rebar.jpg",
    description:
      "Full range of European HEA, HEB, IPE, and American W-shape wide-flange structural steel beams for industrial steel sheds, warehouses, and overhead cranes.",
    features: [
      "High yield strength steel sections with strict dimensional tolerance",
      "Shot-blasted and pre-primed red oxide rust preventive coating available",
      "Direct warehouse sawing, drilling, and mitre cutting service",
      "Full metallurgical traceability with heat numbers stamped on each beam",
    ],
    specs: {
      "Profile Types": "HEA 100 to 1000, HEB 100 to 1000, IPE 80 to 600",
      "Steel Grade": "S355JR high-yield structural steel (355 MPa)",
      "Standard Lengths": "12.0 meters and 15.0 meters factory lengths",
      "Charpy V-Notch": "27 Joules minimum impact energy at 20°C",
      "Inspection": "Third-party inspection verified (SGS / TUV / Bureau Veritas)",
    },
    warranty: "Certified Mill Test Certificate Backing",
  },
  {
    id: "mp-steel-03",
    sku: "MP-PIPE-API",
    title: "API 5L Grade B / X52 Seamless Carbon Steel Linepipes",
    category: "Structural Steel & Construction Rebar",
    origin: "Japan, South Korea & Western Europe",
    leadTime: "Ex-Stock Yard / 2 - 4 Weeks",
    compliance: "API Spec 5L PSL-1 & PSL-2, ASTM A106 Grade B, NACE MR0175",
    image: "/maxpak/industrial_valves_piping.jpg",
    description:
      "Seamless heavy-wall carbon steel linepipes engineered for high-pressure gas distribution, steam boilers, oil transmission, and industrial fluid transport.",
    features: [
      "100% non-destructive ultrasonic and hydrostatic pressure tested",
      "Beveled ends with protective plastic end caps ready for orbital welding",
      "Anti-corrosion external black varnish or 3-layer polyethylene (3LPE) wrap",
      "Supplied in random lengths 5.8m to 12.2m with heat numbers stenciled",
    ],
    specs: {
      "Nominal Pipe Size": "1/2 inch to 24 inch nominal diameters",
      "Schedules": "SCH 40, SCH 80, SCH 160, and SCH XXS heavy wall",
      "Pressure Test": "Hydrostatically tested up to 5,000 PSI",
      "Yield Strength": "52,000 PSI (360 MPa) minimum for X52 PSL-2",
      "Metallurgy": "Low-sulfur killed carbon steel with vacuum degassing",
    },
    warranty: "Full API Monogram & Material Test Traceability",
  },
  {
    id: "mp-steel-04",
    sku: "MP-PLATE-516",
    title: "ASTM A516 Grade 70 Pressure Vessel Quality Steel Plates",
    category: "Structural Steel & Construction Rebar",
    origin: "Germany, Belgium & Japan",
    leadTime: "Ex-Stock Lahore/Karachi",
    compliance: "ASTM A516/A516M Grade 70, ASME SA516 Gr. 70, NACE TM0284",
    image: "/maxpak/structural_steel_rebar.jpg",
    description:
      "Normalized carbon steel boiler plates with high notch toughness for fabricators of steam boilers, industrial pressure vessels, and storage tanks.",
    features: [
      "Normalized heat treatment ensuring fine ferritic grain structure",
      "Tested for Hydrogen Induced Cracking (HIC) and SSCC resistance",
      "Ultrasonically tested to ASTM A578 Level II zero internal lamination",
      "Flame and plasma precision CNC cutting to customer shop drawings",
    ],
    specs: {
      "Thickness Range": "6 mm to 120 mm heavy plate thickness",
      "Plate Dimensions": "2,500 mm x 8,000 mm / 3,000 mm x 12,000 mm",
      "Tensile Strength": "70,000 to 90,000 PSI (485 to 620 MPa)",
      "Impact Toughness": "Charpy impact tested down to -46°C",
      "Condition": "Fully normalized (N) with vacuum degassing",
    },
    warranty: "Full ASME / ASTM Metallurgical Compliance Certificate",
  },

  // ─── 3. HEAVY EARTHMOVING & LIFTING FLEET ───
  {
    id: "mp-fleet-01",
    sku: "MP-EXCAV-50",
    title: "50-Ton Heavy Hydraulic Crawler Excavator",
    category: "Heavy Earthmoving & Lifting Fleet",
    origin: "Japan (CAT / Komatsu / Volvo Authorized Stock)",
    leadTime: "Immediate Delivery from Port Yard",
    compliance: "CE, Tier 4 Final / Stage V Emissions, ISO 12117-2 ROPS/FOPS",
    image: "/maxpak/earthmoving_excavators.jpg",
    description:
      "Massive 50-metric-ton hydraulic crawler excavator engineered for quarrying, highway rock blasting, deep canal excavation, and heavy site earthworks.",
    features: [
      "High-output 298 kW turbocharged diesel engine with dual hydraulic pumps",
      "Heavy-duty 3.2 cubic meter rock bucket with Esco tooth system",
      "Air-conditioned ROPS/FOPS operator cabin with 360-degree surround cameras",
      "Pre-plumbed auxiliary hydraulic piping for rock breaker hammer attachments",
    ],
    specs: {
      "Operating Weight": "49,500 kg (50 Metric Tons)",
      "Engine Power": "400 HP (298 kW) Tier 4F Turbocharged Diesel",
      "Max Digging Depth": "7,650 mm (25.1 ft) digging reach",
      "Bucket Capacity": "3.2 m³ Heavy-Duty Hardox Rock Bucket",
      "Hydraulic Flow": "2 x 380 L/min dual variable piston pumps",
    },
    warranty: "2-Year / 4,000-Hour Powertrain Warranty",
  },
  {
    id: "mp-fleet-02",
    sku: "MP-CRANE-500",
    title: "500-Ton All-Terrain Heavy Industrial Mobile Crane",
    category: "Heavy Earthmoving & Lifting Fleet",
    origin: "Germany (Liebherr / Demag)",
    leadTime: "Immediate Delivery / Site Mobilization",
    compliance: "EN 13000 Mobile Crane Safety, OSHA, CE",
    image: "/maxpak/mobile_crane.jpg",
    description:
      "Flagship 500-ton 8-axle all-terrain mobile crane equipped with telescopic boom and luffing fly jib for heavy power plant and refinery vessel erection.",
    features: [
      "8-axle steering carrier with hydro-pneumatic active axle suspension",
      "84-meter 7-section high-tensile steel telescopic main boom",
      "Modular counterweight package up to 165 metric tons",
      "Liccon computer load moment indicator (LMI) with real-time wind telemetry",
    ],
    specs: {
      "Max Lifting Capacity": "500 Metric Tons at 3.0 m radius",
      "Main Boom Length": "16.1 m to 84.0 m full telescopic extension",
      "Max Hoist Height": "142 m with luffing lattice fly jib",
      "Drive / Steering": "16 x 8 x 16 all-wheel active multi-steering",
      "Engine": "6-Cylinder 505 kW carrier / 240 kW crane superstructure",
    },
    warranty: "Certified Annual Load Test & Third-Party Inspection",
  },
  {
    id: "mp-fleet-03",
    sku: "MP-LOADER-06",
    title: "6.0 m³ Heavy Heavy-Duty Wheel Loader",
    category: "Heavy Earthmoving & Lifting Fleet",
    origin: "Japan & USA",
    leadTime: "Ex-Stock Port",
    compliance: "Tier 4 Final Emissions, ISO 3471 ROPS Cabin",
    image: "/maxpak/earthmoving_excavators.jpg",
    description:
      "High-production quarry and aggregate wheel loader with 6.0 m³ spade-nose bucket, powershift transmission, and heavy planetary final drives.",
    features: [
      "Electronically controlled hydrostatic powertrain with auto-digging cycle",
      "Ride control suspension damping boom bounce over rough terrain",
      "Heated air-ride seat with joystick steering and integrated payload scale",
      "Heavy armored quarry rock tires with optional tire protection chains",
    ],
    specs: {
      "Operating Weight": "32,000 kg",
      "Engine Power": "395 HP (295 kW) heavy diesel",
      "Bucket Capacity": "6.0 m³ high-abrasion spade bucket",
      "Static Tipping Load": "22,500 kg straight / 19,500 kg full turn",
      "Breakout Force": "240 kN hydraulic breakout force",
    },
    warranty: "2-Year / 3,000-Hour Factory Warranty",
  },
  {
    id: "mp-fleet-04",
    sku: "MP-FORK-32",
    title: "32-Ton Heavy Heavy-Duty Industrial Forklift",
    category: "Heavy Earthmoving & Lifting Fleet",
    origin: "Sweden & Germany (Konecranes / Kalmar)",
    leadTime: "3 - 5 Weeks",
    compliance: "ANSI/ITSDF B56.1 Industrial Truck Safety, CE",
    image: "/maxpak/commercial_warehouse.jpg",
    description:
      "Heavy industrial mast forklift designed for steel stockyards, seaport container terminals, and precast concrete manufacturing yards.",
    features: [
      "Heavy-duty duplex mast with hydraulic sideshift and fork positioner",
      "Cummins QSB 6.7 diesel engine paired with Dana powershift transmission",
      "Wet disc hydraulic brakes ensuring zero brake fade under maximum tonnage",
      "High-visibility operator cabin with load weight display",
    ],
    specs: {
      "Rated Capacity": "32,000 kg (32 Metric Tons) at 1,200 mm load center",
      "Lift Height": "5,000 mm standard duplex mast lift",
      "Engine Power": "194 kW (260 HP) industrial diesel",
      "Forks": "2,400 mm forged alloy steel forks with hydraulic spread",
      "Tires": "Solid pneumatic puncture-proof industrial tires",
    },
    warranty: "2-Year Warranty with Scheduled Maintenance Program",
  },

  // ─── 4. INDUSTRIAL VALVES & PIPELINE FITTINGS ───
  {
    id: "mp-valve-01",
    sku: "MP-VALVE-BALL",
    title: "API 6D Trunnion-Mounted High-Pressure Ball Valves",
    category: "Industrial Valves & Pipeline Fittings",
    origin: "Italy, USA & South Korea",
    leadTime: "Ex-Stock / 3 - 6 Weeks Custom Trim",
    compliance: "API 6D, ASME B16.34, API 607 Fire-Safe, NACE MR0175",
    image: "/maxpak/industrial_valves_piping.jpg",
    description:
      "Forged steel trunnion-mounted pipeline ball valves engineered for crude oil, natural gas, sour gas transmission, and petrochemical process loops.",
    features: [
      "Double Block and Bleed (DBB) design with independent spring-energized seats",
      "API 607 and API 6FA certified fire-safe graphite secondary stem packing",
      "Electroless Nickel Plating (ENP) or Inconel 625 overlay on ball and seat rings",
      "Factory-mounted pneumatic or electric quarter-turn rotary actuator",
    ],
    specs: {
      "Size Range": "2 inch to 36 inch nominal bore sizes",
      "Pressure Classes": "ASME Class 150, 300, 600, 900, 1500, and 2500",
      "Body Material": "Forged Carbon Steel A105, Low-Temp A350 LF2, F316 Stainless",
      "Testing": "100% Hydrostatic shell test to 1.5x rating & high-pressure gas test",
      "Temperature Range": "-46°C Low-Temp to +200°C High-Temp Process",
    },
    warranty: "5-Year Pressure Boundary Integrity Guarantee",
  },
  {
    id: "mp-valve-02",
    sku: "MP-VALVE-CTRL",
    title: "Severe-Service Pneumatic Globe Control Valve with Smart Positioner",
    category: "Industrial Valves & Pipeline Fittings",
    origin: "Germany & USA (Fisher / Samson Equivalent)",
    leadTime: "4 - 8 Weeks",
    compliance: "IEC 60534 Control Valve Standards, ATEX, SIL-3 Certified",
    image: "/maxpak/industrial_valves_piping.jpg",
    description:
      "Precision modulating globe control valve equipped with multi-stage anti-cavitation trim and HART-enabled digital smart valve positioner.",
    features: [
      "Multi-hole anti-cavitation cage trim eliminating noise and trim erosion",
      "Micro-processor controlled HART/Foundation Fieldbus positioner with 4-20mA feedback",
      "Live-loaded PTFE/graphite chevron stem packing resisting fugitive emissions",
      "Quick-change seat ring allowing rapid in-line maintenance without valve removal",
    ],
    specs: {
      "Bore Sizes": "1 inch to 12 inch flanged and butt-weld connections",
      "Pressure Rating": "ASME Class 150 to Class 2500",
      "Flow Characteristic": "Equal Percentage, Linear, or Quick-Opening",
      "Shut-off Class": "ANSI/FCI 70-2 Class IV, Class V, or Class VI Bubble-Tight",
      "Actuator": "Multi-spring pneumatic diaphragm actuator with manual handwheel",
    },
    warranty: "3-Year Process Control Assurance Warranty",
  },
  {
    id: "mp-valve-03",
    sku: "MP-FLANGE-1500",
    title: "ASME B16.5 Forged Steel Weld Neck & Blind Flanges",
    category: "Industrial Valves & Pipeline Fittings",
    origin: "Italy, Japan & South Korea",
    leadTime: "Immediate Ex-Stock Warehouse",
    compliance: "ASME B16.5, ASTM A105N, ASTM A182 F316L, NACE MR0103",
    image: "/maxpak/industrial_valves_piping.jpg",
    description:
      "Heavy forged carbon steel and stainless steel weld-neck, blind, and slip-on flanges with raised face (RF) or ring type joint (RTJ) facings.",
    features: [
      "Closed-die hot forged metallurgy ensuring uniform grain flow and zero porosity",
      "Serrated spiral concentric phonographic finish (125 - 250 AARH) for gasket sealing",
      "Full material test reports (MTR) with heat treatment batch certification",
      "Chamfered weld prep bore matching schedule 40, schedule 80, or schedule 160 pipes",
    ],
    specs: {
      "Flange Types": "Weld Neck (WN), Blind (BL), Slip-On (SO), Socket Weld (SW)",
      "Sizes": "1/2 inch to 48 inch nominal pipe dimensions",
      "Pressure Ratings": "Class 150, 300, 600, 900, 1500, and 2500 RTJ",
      "Material Grades": "ASTM A105N Normalized, A350 LF2, A182 F304/F316L, Inconel",
      "Markings": "Die-stamped size, rating, grade, schedule, and heat code number",
    },
    warranty: "Full Dimensional & Metallurgical MTC Certification",
  },
  {
    id: "mp-valve-04",
    sku: "MP-PUMP-SLURRY",
    title: "Heavy-Duty Chemical & Slurry Centrifugal Process Pump",
    category: "Industrial Valves & Pipeline Fittings",
    origin: "Germany & Japan (KSB / Warman Technology)",
    leadTime: "4 - 7 Weeks",
    compliance: "API 610 11th Edition, ISO 5199 Chemical Pumps, ATEX",
    image: "/maxpak/industrial_valves_piping.jpg",
    description:
      "Heavy-duty horizontal end-suction centrifugal slurry pump with high-chrome alloy wet end engineered for abrasive mining slurries and aggressive chemicals.",
    features: [
      "High-chrome 27% white cast iron replaceable casing liners and impeller",
      "Cartridge mechanical seal with dual pressurized barrier fluid system",
      "Heavy bearing assembly with labyrinth oil seals and grease purge fittings",
      "Externally adjustable impeller clearance maintaining maximum pump efficiency",
    ],
    specs: {
      "Flow Capacity": "Up to 3,500 m³/hour continuous flow volume",
      "Discharge Head": "Up to 110 meters total dynamic head (TDH)",
      "Solids Handling": "Handles slurries with up to 65% solids by weight",
      "Drive System": "Direct flexible coupling or heavy V-belt electric motor drive",
      "Power Rating": "15 kW to 450 kW severe-duty TEFC electric motors",
    },
    warranty: "2-Year Mechanical & Impeller Abrasion Warranty",
  },

  // ─── 5. ELECTRICAL SWITCHGEAR & POWER SYSTEMS ───
  {
    id: "mp-pwr-01",
    sku: "MP-SWG-11KV",
    title: "11kV Indoor Metal-Clad Vacuum Circuit Breaker Switchgear",
    category: "Electrical Switchgear & Power Systems",
    origin: "Germany & Switzerland (ABB / Schneider Electric Equivalent)",
    leadTime: "6 - 10 Weeks Custom Engineered",
    compliance: "IEC 62271-200, WAPDA S-11 Certified, ISO 9001",
    image: "/maxpak/electrical_switchgear.jpg",
    description:
      "Type-tested 11kV air-insulated metal-clad indoor switchgear panel equipped with withdrawable vacuum circuit breaker for industrial utility distribution.",
    features: [
      "Hermetically sealed ceramic vacuum interrupters rated for 30,000 operations",
      "Internal arc classification (IAC AFLR 25kA 1s) ensuring maximum operator safety",
      "Microprocessor-based digital protection relays (overcurrent, earth fault, differential)",
      "Mechanical and electrical interlocks preventing inadvertent operation while energized",
    ],
    specs: {
      "Rated Voltage": "12 kV nominal operating voltage",
      "Rated Current": "630A, 1,250A, 2,000A, and 3,150A continuous busbar rating",
      "Short-Circuit Breaking": "25 kA / 31.5 kA for 3 seconds",
      "Impulse Withstand": "75 kV BIL lightning impulse test level",
      "Degree of Protection": "IP4X metal enclosure / IP2X internal compartments",
    },
    warranty: "3-Year Electrical Integrity & Relay Guarantee",
  },
  {
    id: "mp-pwr-02",
    sku: "MP-XFMR-25MVA",
    title: "25 MVA 132kV / 11kV Oil-Immersed Grid Power Transformer",
    category: "Electrical Switchgear & Power Systems",
    origin: "Germany & South Korea",
    leadTime: "12 - 16 Weeks Heavy Haul Delivery",
    compliance: "IEC 60076 Power Transformers, IEEE C57, CE",
    image: "/maxpak/electrical_switchgear.jpg",
    description:
      "Heavy utility-scale three-phase oil-immersed power transformer with On-Load Tap Changer (OLTC) for industrial parks, grid substations, and captive power plants.",
    features: [
      "High-permeability cold-rolled grain-oriented (CRGO) magnetic silicon steel core",
      "Electrolytic grade copper conductor windings with thermally upgraded paper insulation",
      "MR Reinhausen motorized on-load tap changer with 17 voltage regulation steps",
      "Equipped with Buchholz relay, pressure relief valve, and digital winding temperature telemetry",
    ],
    specs: {
      "Rated Capacity": "20 / 25 MVA ONAN / ONAF cooling capacity",
      "Voltage Ratio": "132,000 Volts Primary to 11,000 Volts Secondary",
      "Frequency": "50 Hz 3-Phase alternating current",
      "Vector Group": "YNd11 standard vector configuration",
      "Insulating Fluid": "High-dielectric mineral transformer oil (PCB-Free)",
    },
    warranty: "5-Year Grid Transformer Operational Guarantee",
  },
  {
    id: "mp-pwr-03",
    sku: "MP-MCC-LV",
    title: "Low-Voltage Intelligent Motor Control Center (iMCC) Panels",
    category: "Electrical Switchgear & Power Systems",
    origin: "European Technology Assembly",
    leadTime: "4 - 7 Weeks",
    compliance: "IEC 61439-1/2 Form 4b Segregation, CE",
    image: "/maxpak/electrical_switchgear.jpg",
    description:
      "Fully withdrawable intelligent Motor Control Center (iMCC) panels featuring variable frequency drives (VFDs) and soft starters for heavy process plants.",
    features: [
      "Form 4b internal physical segregation of busbars, functional units, and terminals",
      "Integrated ABB / Danfoss VFDs with active harmonic mitigation filters",
      "EtherNet/IP and Modbus-TCP communication bus connecting to plant DCS/SCADA",
      "Draw-out functional starter buckets allowing live maintenance without line stoppage",
    ],
    specs: {
      "Operating Voltage": "415V / 690V 3-Phase 50 Hz",
      "Busbar Current": "Up to 4,000A high-purity tinned copper busbars",
      "Short-Circuit Level": "50 kA / 65 kA for 1 second",
      "Motor Starter Range": "0.75 kW fractional to 350 kW heavy drive units",
      "Enclosure Protection": "IP54 sheet steel enclosure with anti-corrosion powder coating",
    },
    warranty: "2-Year Comprehensive Panel Warranty",
  },
  {
    id: "mp-pwr-04",
    sku: "MP-GEN-2000",
    title: "2,000 kVA Heavy Containerized Prime Diesel Generator Set",
    category: "Electrical Switchgear & Power Systems",
    origin: "UK & USA (Cummins / Perkins / Stamford)",
    leadTime: "Immediate Ex-Stock Lahore / Karachi",
    compliance: "ISO 8528 Generator Set Standards, CE, EPA Tier 2/3",
    image: "/maxpak/electrical_switchgear.jpg",
    description:
      "Containerized heavy diesel power generator set designed for continuous prime power and emergency black-start backup for industrial facilities.",
    features: [
      "Cummins QSK60 16-cylinder heavy turbocharged electronic fuel-injected engine",
      "Stamford brushless self-excited alternator with automatic voltage regulator (AVR)",
      "Weatherproof, sound-attenuated ISO 20ft container with residential silencer (75 dBA at 1m)",
      "Deep Sea Electronics (DSE 8610) automatic synchronizing and load-sharing controller",
    ],
    specs: {
      "Prime Output": "1,800 kVA (1,440 kW) continuous prime rating",
      "Standby Output": "2,000 kVA (1,600 kW) emergency standby rating",
      "Output Voltage": "415/240V 50 Hz 1,500 RPM 3-Phase",
      "Fuel Autonomy": "Built-in 2,500 liter dual-wall daily fuel storage tank",
      "Fuel Consumption": "Low specific fuel consumption rate at 75% prime load",
    },
    warranty: "2-Year / 2,000-Hour Factory Powertrain Warranty",
  },

  // ─── 6. TURNKEY EPC PLANTS & COMMERCIAL SUPPLIES ───
  {
    id: "mp-epc-01",
    sku: "MP-BOILER-20T",
    title: "20 Ton/Hour Industrial Water Tube Steam Boiler Package",
    category: "Turnkey EPC Plants & Commercial Supplies",
    origin: "Germany & Japan (Viessmann / Babcock Equivalent)",
    leadTime: "10 - 14 Weeks Turnkey Erection",
    compliance: "ASME Boiler and Pressure Vessel Code Section I, CE PED 2014/68/EU",
    image: "/maxpak/epc_plant.jpg",
    description:
      "Complete packaged industrial steam boiler plant including multi-fuel burner, economizer, deaerator, water softener, and automated blowdown systems.",
    features: [
      "Three-pass wet-back water tube design delivering over 92% thermal efficiency",
      "Dual-fuel gas and light oil modulating low-NOx industrial burner",
      "Automated PLC boiler master control panel with continuous flue gas oxygen monitoring",
      "Complete feedwater chemical dosing station and condensate recovery systems",
    ],
    specs: {
      "Steam Output": "20,000 kg/hour (20 Metric Tons/Hour) continuous steam",
      "Design Pressure": "25 Bar (360 PSI) maximum operating pressure",
      "Steam Temperature": "Saturated or superheated up to 350°C",
      "Thermal Efficiency": "92.5% with integrated condensing flue gas economizer",
      "Commissioning": "On-site hydrostatic pressure test and third-party inspection sign-off",
    },
    warranty: "5-Year Pressure Vessel Shell Warranty",
  },
  {
    id: "mp-epc-02",
    sku: "MP-VESSEL-ASME",
    title: "ASME Section VIII Div. 1 Custom Process Pressure Vessels",
    category: "Turnkey EPC Plants & Commercial Supplies",
    origin: "Certified Heavy Fabrication Facilities",
    leadTime: "8 - 12 Weeks",
    compliance: "ASME 'U' Stamp, National Board Registered, PED 2014/68/EU",
    image: "/maxpak/epc_plant.jpg",
    description:
      "Custom engineered distillation columns, gas separators, and horizontal knock-out drums fabricated from carbon steel, stainless steel, and clad alloys.",
    features: [
      "100% full radiography (RT) inspection on all longitudinal and circumferential welds",
      "Post-Weld Heat Treatment (PWHT) in computer-controlled car-bottom furnaces",
      "Internals including demister pads, inlet distribution baffles, and vortex breakers",
      "Supplied with complete ASME Manufacturer Data Report (Form U-1)",
    ],
    specs: {
      "Diameter Range": "Up to 4,500 mm internal diameter",
      "Wall Thickness": "12 mm to 80 mm heavy plate shell",
      "Design Pressure": "Full vacuum up to 150 Bar (2,175 PSI)",
      "Materials": "SA516 Gr. 70, SA240 316L Stainless, SA387 Gr. 11 Chrome-Moly",
      "Corrosion Allowance": "3.0 mm to 6.0 mm standard process allowance",
    },
    warranty: "10-Year ASME Certified Structural Integrity",
  },
  {
    id: "mp-epc-03",
    sku: "MP-COMM-RACK",
    title: "Heavy-Duty Industrial Pallet Racking & Automated Warehouse Systems",
    category: "Turnkey EPC Plants & Commercial Supplies",
    origin: "European Manufacturing Standards",
    leadTime: "2 - 4 Weeks Installation",
    compliance: "SEMA Guidelines, EN 15512 Racking Standards, ISO 9001",
    image: "/maxpak/commercial_warehouse.jpg",
    description:
      "High-density pallet racking systems, drive-in racks, and automated storage and retrieval systems (ASRS) for corporate logistics hubs.",
    features: [
      "High-strength cold-formed steel uprights with electrostatic epoxy powder finish",
      "Adjustable beam connector locks with safety spring pins preventing dislodgement",
      "Integrated upright column crash protectors, guide rails, and timber/steel mesh decking",
      "Turnkey structural layout design, floor anchoring, and load capacity certification",
    ],
    specs: {
      "Beam Span": "2,700 mm and 3,600 mm for 2 or 3 standard Euro/ISO pallets",
      "Load Capacity": "Up to 4,000 kg per beam level uniformly distributed",
      "Racking Height": "3.0 meters up to 14.0 meters vertical storage height",
      "Finish": "Pre-treated shot blasted polyester powder coating",
      "Seismic Rating": "Engineered for Zone 2B and Zone 3 seismic load resistance",
    },
    warranty: "5-Year Structural Frame Warranty",
  },
  {
    id: "mp-epc-04",
    sku: "MP-COMM-SAFETY",
    title: "Complete Enterprise Safety PPE & Industrial Plant Supplies Suite",
    category: "Turnkey EPC Plants & Commercial Supplies",
    origin: "USA & Europe (3M / Honeywell / MSA Equivalent)",
    leadTime: "Immediate Ex-Stock Warehouse Supply",
    compliance: "ANSI Z87.1, OSHA 1910, EN 397 Helmet Standard, ISO 20345",
    image: "/maxpak/quality_inspection.jpg",
    description:
      "Bulk institutional supply of certified industrial personal protective equipment (PPE), gas detectors, spill containment kits, and facility maintenance supplies.",
    features: [
      "Hardhats, anti-scratch safety glasses, flame-retardant Nomex boiler suits, and steel-toe boots",
      "Portable 4-gas atmospheric monitors (O2, LEL, CO, H2S) with wireless data logging",
      "Heavy chemical spill response containment booms, drum absorbents, and lockout/tagout (LOTO) kits",
      "Dedicated corporate monthly replenishment contracts with bulk institutional pricing",
    ],
    specs: {
      "Safety Certifications": "CE EN certified, ANSI standards compliant",
      "Supply Formats": "Pre-packaged site startup kits or bulk pallet crates",
      "Inventory Holding": "Over 50,000 safety units in stock ready for immediate dispatch",
      "Customization": "Corporate silkscreen logo printing and custom reflective striping",
      "Emergency Delivery": "24-hour turnaround for critical shutdown and turnaround supplies",
    },
    warranty: "100% Certified PPE Standards Guarantee",
  },
];

export const PROCESS_STEPS = [
  {
    num: "01",
    title: "Engineering Consultation & Requirement Sizing",
    desc: "Our senior industrial engineers audit technical specifications, duty cycles, operating pressures, and mechanical tolerances to recommend the optimal equipment and materials.",
  },
  {
    num: "02",
    title: "Direct OEM Sourcing & Mill Allocation",
    desc: "We leverage 30+ years of direct relationships with certified manufacturers across Germany, Japan, USA, and Europe, eliminating intermediaries and guaranteeing competitive factory-gate pricing.",
  },
  {
    num: "03",
    title: "Third-Party Pre-Shipment Quality Testing",
    desc: "Every order undergoes strict third-party inspection (SGS, TUV, Bureau Veritas), verifying Mill Test Certificates (EN 10204 3.1), dimensional tolerances, and ultrasonic non-destructive testing (NDT).",
  },
  {
    num: "04",
    title: "Port Customs Clearance & Bonded Yard Logistics",
    desc: "Our licensed in-house customs brokerage manages automated electronic filing, tariff classification optimization, and expedited green-channel release without costly port demurrage.",
  },
  {
    num: "05",
    title: "Heavy Haulage & Scheduled Site Delivery",
    desc: "We operate a dedicated fleet of multi-axle heavy-haul trailers, lowbeds, and flatbeds equipped with real-time GPS tracking to deliver directly to your plant site on schedule.",
  },
  {
    num: "06",
    title: "On-Site Erection, Commissioning & Spares Buffer",
    desc: "Our field service engineers supervise mechanical positioning, electrical termination, pre-commissioning video trials, and maintain an emergency 24-hour OEM spare parts buffer.",
  },
];

export const PROJECT_CASE_STUDIES = [
  {
    id: "cs-cpec-machinery",
    title: "CPEC Motorway Heavy Machinery Fleet Procurement",
    category: "Heavy Earthmoving & Lifting Fleet",
    client: "National Highway EPC Consortium",
    scope: "85 Heavy Hydraulic Excavators, Bulldozers & Asphalt Plants",
    desc: "Turnkey procurement, pre-shipment SGS inspection, chartered ocean vessel dispatch, and expedited green-channel customs clearance for 85 heavy machines with zero downtime over 24 months.",
    image: "/maxpak/earthmoving_excavators.jpg",
    tag: "Earthmoving Fleet",
    metrics: ["85 Heavy Units Delivered", "100% On-Schedule Mobilization", "0 Lost-Time Incidents"],
  },
  {
    id: "cs-grid-substation",
    title: "National Grid 500kV High-Voltage Switchgear & Transformers",
    category: "Electrical Switchgear & Power Systems",
    client: "National Transmission & Dispatch Co. (NTDC)",
    scope: "12 Extra-Heavy 180-Ton 500kV Power Transformers & GIS Bays",
    desc: "Coordinating precision heavy-lift ocean shipping, hydraulic multi-axle overland road convoys with zero vibration, and on-site testing for twelve 500kV grid transformers.",
    image: "/maxpak/electrical_switchgear.jpg",
    tag: "Grid Power Trade",
    metrics: ["12 Units (180 Tons Each)", "Zero-Vibration Transport", "500kV Grid Energization"],
  },
  {
    id: "cs-refinery-piping",
    title: "Petrochemical Refinery API 5L Pipeline & Severe-Service Valves",
    category: "Industrial Valves & Pipeline Fittings",
    client: "National Oil Refinery Expansion Project",
    scope: "120 km API 5L Seamless Casings & 450 Trunnion Ball Valves",
    desc: "Supplied 120 kilometers of API 5L Grade X65 pipeline casing with 3LPE external wrap, along with 450 Class 1500 forged steel trunnion ball valves tested for severe sour gas service.",
    image: "/maxpak/industrial_valves_piping.jpg",
    tag: "Refinery Supply",
    metrics: ["120 km High-Pressure Pipe", "100% Ultrasonic NDT Tested", "NACE MR0175 Compliant"],
  },
];

export const FAQS = [
  {
    q: "What industrial sectors does Max Pak Corporation supply?",
    a: "We supply 12+ major industrial sectors across Pakistan and the region, including Heavy Construction & Infrastructure, Oil, Gas & Petrochemical Refineries, Power Generation & Electric Substations, Manufacturing Plants, Mining & Cement Operations, and Corporate Commercial Logistics.",
  },
  {
    q: "Do your structural steel and linepipe products come with Mill Test Certificates (MTC)?",
    a: "Yes. 100% of our structural steel rebar, H-beams, plates, and API linepipes are supplied with certified EN 10204 3.1 Mill Test Certificates (MTCs), providing full chemical composition analysis, mechanical tensile test reports, and heat number traceability stamped directly onto each piece.",
  },
  {
    q: "Can Max Pak Corporation handle turnkey EPC procurement packages?",
    a: "Absolutely. We specialize in turnkey procurement for large-scale engineering projects. We manage manufacturer contract negotiations, Letters of Credit (LC), third-party inspections (SGS/TUV), international maritime shipping, customs clearance, and synchronized multi-axle delivery to your project site.",
  },
  {
    q: "What is your emergency delivery capability for critical industrial spare parts?",
    a: "Through our centralized logistics hubs in Lahore and Karachi, we maintain dedicated inventory buffers of critical valves, switchgear circuit breakers, and heavy machinery spares available for emergency 24-hour dispatch to minimize unplanned plant downtime.",
  },
  {
    q: "Can you provide customized technical specifications for non-standard equipment?",
    a: "Yes. Our team of senior mechanical and electrical engineers works directly with your engineering department to review drawings, operating pressures, temperatures, and duty cycles, custom-ordering tailored machinery and pressure vessels built to exact ASME, API, or DIN standards.",
  },
];
